import { useEffect, useRef } from 'react';
import type { Snapshot } from '../../domain/snapshot';
import { sourceAgeLabel } from '../../domain/sources';

function formatDate(iso: string) { return Number.isFinite(Date.parse(iso)) ? new Intl.DateTimeFormat('es-AR', { day: '2-digit', month: 'short', hour: '2-digit', minute: '2-digit', timeZone: 'America/Argentina/Cordoba' }).format(new Date(iso)) : 'sin timestamp'; }

export function DetailsDialog({ snapshot, open, onClose }: { readonly snapshot: Snapshot; readonly open: boolean; readonly onClose: () => void }) {
  const ref = useRef<HTMLDialogElement>(null);
  useEffect(() => { const dialog = ref.current; if (!dialog) return; if (open && !dialog.open) dialog.showModal(); if (!open && dialog.open) dialog.close(); }, [open]);
  return <dialog ref={ref} className="details-dialog evidence-sheet" aria-labelledby="details-title" onClose={onClose} onClick={(event) => { if (event.target === event.currentTarget) onClose(); }}><div className="evidence-surface"><div className="dialog-head"><div><span className="v3-eyebrow">Trazabilidad</span><h2 id="details-title">Evidencia y vigencia</h2></div><button className="ui-icon-button" type="button" onClick={onClose} aria-label="Cerrar evidencia">×</button></div><p className="dialog-lead">Cada estación conserva su propia escala, fuente y timestamp. Una fuente desactualizada no se presenta como lectura actual.</p><section className="dialog-section"><h3>Sistemas hídricos</h3><div className="source-detail-list">{(snapshot.systems ?? []).map((system) => <article className="source-detail" key={system.id}><div><span className={`source-dot source-dot--${system.dataStatus.toLowerCase()}`} aria-hidden="true"/><strong>{system.label} · {system.stationName}</strong></div><p>{system.available && system.currentMetres !== null ? `${system.currentMetres.toFixed(2)} m · ${system.trend}` : 'Sin datos en vivo'}</p><small>{system.sourceName} · {system.observedAt ? sourceAgeLabel(system.observedAt, snapshot.generatedAt) : 'sin lectura'} · {formatDate(system.observedAt ?? '')}</small><code>{system.sourceId}</code></article>)}</div></section><section className="dialog-section"><h3>Fuentes consultadas</h3><div className="source-detail-list">{snapshot.sources.length ? snapshot.sources.map((source) => <article key={source.id} className="source-detail"><div><span className={`source-dot source-dot--${source.status.toLowerCase()}`} aria-hidden="true"/><strong>{source.name}</strong></div><p>{source.contribution}</p><small>{source.kind.replaceAll('_', ' ')} · {source.status} · {sourceAgeLabel(source.observedAt, snapshot.generatedAt)} · vigencia {formatDate(source.validUntil)}</small>{source.latencyMinutes && <small>Latencia declarada: {source.latencyMinutes} min{source.resolution ? ` · resolución ${source.resolution}` : ''}</small>}<code>{source.id}</code></article>) : <p>Sin fuentes disponibles.</p>}</div></section><section className="dialog-section"><h3>Cómo se usa la información</h3><p>Las observaciones oficiales se muestran por estación. NASA GPM, cuando está disponible, es una estimación satelital suplementaria y no reemplaza mediciones de superficie. No se raspa HTML ni se sustituyen estaciones silenciosamente.</p></section><section className="dialog-section"><h3>Estado técnico</h3><p><a href="/api/health">Comprobar salud de la API</a> · <a href="/api/sources">Ver fuentes JSON</a>.</p></section><button className="ui-button ui-button--primary" type="button" onClick={onClose}>Cerrar</button></div></dialog>;
}
