import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';
const app=fs.readFileSync('public/app.js','utf8'),html=fs.readFileSync('public/index.html','utf8'),sw=fs.readFileSync('public/service-worker.js','utf8'),css=fs.readFileSync('public/app.css','utf8');
test('LOCATION_NOT_REQUESTED_ON_LOAD',()=>{const call=app.indexOf('getCurrentPosition');const click=app.lastIndexOf("$('#use-location').onclick",call);assert.ok(call>0&&click>=0&&click<call);assert.doesNotMatch(html,/autofocus/i)});
test('GEOLOCATION_DENIED_APP_WORKS through manual selection path',()=>{assert.match(app,/Ubicación denegada/);assert.match(app,/\/api\/georef\/search/);assert.match(html,/Área inicial · centro del país \(recorte local\)/);assert.match(html,/Elegir localidad/)});
test('watch zones are local-first and no position history storage exists',()=>{assert.match(app,/localStorage\.getItem\('sos-zones'\)/);assert.match(app,/localStorage\.setItem\('sos-zones'/);assert.doesNotMatch(app,/position-history|location-history|watchPosition/)});
test('Argenmap is lazy and no tile/map request exists in initial HTML',()=>{assert.doesNotMatch(html,/id="argenmap"[^>]+src=/);assert.match(app,/wms\.ign\.gob\.ar/);assert.match(app,/renderMap/)});
test('map and list derive from same event collection and expose detail',()=>{assert.match(app,/function renderEvents\(\).*for\(const e of events\).*d\.dataset\.eventId=e\.eventId/s);assert.match(app,/function renderMapMarkers\(\).*for\(const e of events\).*b\.dataset\.mapEventId=e\.eventId.*b\.onclick=\(\)=>openEventDetail\(e\.eventId\)/s);assert.match(app,/\[data-detail\].*openEventDetail\(b\.dataset\.detail\)/s);assert.match(html,/id="event-list"/);assert.match(html,/id="map-markers"/);assert.doesNotMatch(app,/\bmapEvents\b|\bmapEventDataset\b/)});
test('offline live APIs cannot claim current verification or no alerts',()=>{assert.match(sw,/OFFLINE_CANNOT_VERIFY/);assert.match(sw,/canSayNoActiveOfficialWarnings:false/);assert.match(sw,/FUENTES_DE_ALERTAS_NO_DISPONIBLES/);assert.doesNotMatch(sw,/sin alertas/i)});
test('push permission is only requested after explicit opt-in click',()=>{const start=app.indexOf('async function enablePush()'),end=app.indexOf('\nasync function deletePush()',start);assert.ok(start>=0&&end>start);const enablePush=app.slice(start,end);assert.equal((app.match(/Notification\.requestPermission\(\)/g)||[]).length,1);assert.match(enablePush,/Notification\.requestPermission\(\)/);assert.match(app,/\$\('#push-optin'\)\.onclick=enablePush/);assert.match(enablePush,/permission!==['"]granted['"].*La app sigue funcionando sin push/s);assert.match(app,/officialWarnings:true,modelSignals:false,satelliteEstimates:false/)});
test('source roles and limitations are visibly separated',()=>{for(const label of['Alerta oficial','Medición oficial','Contexto oficial de riesgo','Modelo de pronóstico','Estimación satelital'])assert.match(app,new RegExp(label));assert.match(html,/Fuentes y limitaciones/)});
test('accessible basics and reduced motion',()=>{assert.match(html,/Saltar al contenido/);assert.match(html,/aria-live="polite"/);assert.match(html,/<dialog/);assert.match(css,/focus-visible/);assert.match(css,/prefers-reduced-motion/);assert.match(css,/min-height:44px/)});
test('no remote fonts or trackers',()=>{assert.doesNotMatch(html,/fonts\.googleapis|googletagmanager|segment|mixpanel|analytics/i);assert.doesNotMatch(css,/@import|@font-face/)});

test('NATIONAL_OVERVIEW_SEPARATE_FROM_LOCAL_BBOX',()=>{assert.match(html,/Argentina · panorama nacional/);assert.match(html,/Área seleccionada · eventos y evidencia/);assert.match(html,/recorte local/);assert.match(app,/\/api\/overview/);assert.match(app,/\/api\/events\?bbox=/)});
test('PUSH_READ_CREDENTIAL_SERVICE_WORKER_ONLY',()=>{assert.doesNotMatch(app,/localStorage\.(?:setItem|getItem)\('sos-push-read-credential'/);assert.match(sw,/indexedDB\.open\('sos-sf-push'/);assert.match(sw,/SOS_PUSH_SELF_TEST/);assert.match(sw,/SOS_PUSH_DELETE_REMOTE/)});
test('MAP_MARKER_INTERSECTING_EVENT_REMAINS_REPRESENTED',()=>{assert.match(app,/function eventMapPoint\(e\).*Math\.max\(Number\(b\[0\]\),bbox\[0\]\).*Math\.min\(Number\(b\[2\]\),bbox\[2\]\).*west>east\|\|south>north.*return\[\(west\+east\)\/2,\(south\+north\)\/2\]/s);assert.doesNotMatch(app,/function renderMapMarkers\(\).*if\(x<0\|\|x>100\|\|y<0\|\|y>100\)continue/s);const event=[-68.78,-30.74,-65.04,-22.6],view=[-72,-34,-66,-28],west=Math.max(event[0],view[0]),south=Math.max(event[1],view[1]),east=Math.min(event[2],view[2]),north=Math.min(event[3],view[3]);assert.ok(west<=east&&south<=north);const point=[(west+east)/2,(south+north)/2];assert.ok(point[0]>=view[0]&&point[0]<=view[2]&&point[1]>=view[1]&&point[1]<=view[3])});
