import test from'node:test';
import assert from'node:assert/strict';
import fs from'node:fs';
import {DatabaseSync} from'node:sqlite';
import {publicRecord,reconcile} from'../src/domain/hazard.js';
import {handlePush,dispatchRecordNotifications,validPushEndpoint,sendEmptyWebPush} from'../src/worker/push.js';

function db(){const raw=new DatabaseSync(':memory:');for(const f of['migrations/0001-national.sql','migrations/0002-order031.sql','migrations/0003-worker-job-lease.sql'])raw.exec(fs.readFileSync(f,'utf8'));return{raw,prepare(sql){let a=[];return{bind(...x){a=x;return this},async run(){const r=raw.prepare(sql).run(...a);return{meta:{changes:Number(r.changes||0)}}},async all(){return{results:raw.prepare(sql).all(...a)}},async first(){return raw.prepare(sql).get(...a)||null}}}}}
const NOW=Date.parse('2026-08-28T10:00:00Z');
function rr(id,bbox,role='OFFICIAL_WARNING'){return publicRecord({recordId:id,providerId:role==='OFFICIAL_WARNING'?'smn-cap':'ina',providerRecordId:id,hazardType:'STORM',sourceRole:role,sourceOrganization:'X',official:true,issuedAt:'2026-08-28T09:00:00Z',observedAt:role==='OFFICIAL_WARNING'?null:'2026-08-28T09:00:00Z',effectiveAt:null,onsetAt:null,expiresAt:'2026-08-28T14:00:00Z',fetchedAt:'2026-08-28T09:01:00Z',freshness:'FRESH',verificationState:'VERIFIED_MACHINE',geometry:null,bbox,regionCodes:['AR-S'],province:'Santa Fe',headline:id,description:'',instruction:null,sourceUrl:'https://example.invalid',attribution:'X',rawHash:id,lifecycle:'ACTIVE',capIdentifier:role==='OFFICIAL_WARNING'?id:null,capLineageRoot:role==='OFFICIAL_WARNING'?id:null})}

test('FAR_SAME_REGION_CODE_NOT_EVENT_MERGE',()=>assert.equal(reconcile([rr('a',[-60.7,-31.7,-60.6,-31.6]),rr('b',[-65.7,-26.7,-65.6,-26.6])],new Date(NOW)).length,2));
test('DISCONNECTED_SAME_PROVINCE_WARNINGS_SEPARATE_RUNTIME',()=>assert.equal(reconcile([rr('a',[-60.7,-31.7,-60.6,-31.6]),rr('b',[-61.9,-29.8,-61.8,-29.7])],new Date(NOW)).length,2));
test('SIMULTANEOUS_SAME_REGION_EVENTS_REMAIN_SEPARATE',()=>assert.equal(reconcile([rr('a',[-60.7,-31.7,-60.6,-31.6]),rr('b',[-64.7,-27.7,-64.6,-27.6]),rr('obs',[-60.69,-31.69,-60.61,-31.61],'OFFICIAL_LOCAL_OR_NATIONAL_OBSERVATION')],new Date(NOW)).length,2));

test('PUSH_DB_LEGACY_FALLBACK_FORBIDDEN',async()=>{const trap={prepare(){throw new Error('LEGACY_DB_TOUCHED')}};let u=new URL('https://sos-sf.simondalmasso44.workers.dev/api/push/config'),r=await handlePush(new Request(u),{MESSAGES_DB:trap,VAPID_PUBLIC_KEY:'AAA',VAPID_PRIVATE_JWK:'{}',PUSH_STORAGE_KEY:'x'.repeat(32)},u),x=await r.json();assert.equal(x.data.enabled,false);u=new URL('https://sos-sf.simondalmasso44.workers.dev/api/push/subscribe');r=await handlePush(new Request(u,{method:'POST',headers:{origin:'https://sos-sf.simondalmasso44.workers.dev','content-type':'application/json'},body:'{}'}),{MESSAGES_DB:trap,PUSH_STORAGE_KEY:'x'.repeat(32)},u);assert.equal(r.status,503)});
test('HAZARD_DB_REQUIRED_FOR_PUSH_MUTATION',async()=>{const u=new URL('https://sos-sf.simondalmasso44.workers.dev/api/push/zones'),r=await handlePush(new Request(u,{method:'DELETE',headers:{origin:'https://sos-sf.simondalmasso44.workers.dev','content-type':'application/json'},body:JSON.stringify({zoneId:'abcdefgh',subscriptionId:'0'.repeat(64),readCredential:'x'.repeat(32)})}),{PUSH_STORAGE_KEY:'x'.repeat(32)},u);assert.equal(r.status,503)});

test('PUSH_ENDPOINT_WNS_PREFIX_ESCAPE_REJECTED',()=>assert.equal(validPushEndpoint('https://wns2-evil.example.com/push'),false));
test('PUSH_ENDPOINT_ARBITRARY_LOOKALIKE_REJECTED',()=>{for(const x of['https://fcm.googleapis.com.evil.example/p','https://notify.windows.com.evil.example/p','https://push.apple.com.evil.example/p','https://updates.push.services.mozilla.com.evil.example/p'])assert.equal(validPushEndpoint(x),false)});
test('PUSH_ENDPOINT_VERIFIED_SERVICES_ACCEPTED',()=>{for(const x of['https://fcm.googleapis.com/fcm/send/a','https://updates.push.services.mozilla.com/wpush/v2/a','https://web.push.apple.com/a','https://dm3p.notify.windows.com/?token=a'])assert.equal(validPushEndpoint(x),true)});
test('PUSH_REDIRECT_REVALIDATED',async()=>{const pair=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},true,['sign','verify']),jwk=await crypto.subtle.exportKey('jwk',pair.privateKey),old=globalThis.fetch;let seen=null;globalThis.fetch=async(url,init)=>{seen={url:String(url),redirect:init.redirect};return new Response(null,{status:307,headers:{location:'https://evil.example/'}})};try{const r=await sendEmptyWebPush('https://fcm.googleapis.com/fcm/send/a',{VAPID_PUBLIC_KEY:'AAA',VAPID_PRIVATE_JWK:JSON.stringify(jwk)});assert.equal(r.ok,false);assert.equal(r.status,307);assert.deepEqual(seen,{url:'https://fcm.googleapis.com/fcm/send/a',redirect:'manual'})}finally{globalThis.fetch=old}});

async function mkSub(d,label){const env={HAZARD_DB:d,PUSH_STORAGE_KEY:'x'.repeat(32),VAPID_PUBLIC_KEY:'AAA',VAPID_PRIVATE_JWK:'{}'},origin='https://sos-sf.simondalmasso44.workers.dev',u=new URL(origin+'/api/push/subscribe'),r=await handlePush(new Request(u,{method:'POST',headers:{origin,'content-type':'application/json'},body:JSON.stringify({endpoint:`https://fcm.googleapis.com/fcm/send/${label}`,keys:{p256dh:'a'.repeat(32),auth:'b'.repeat(16)}})}),env,u),x=await r.json();return{env,origin,sid:x.data.subscriptionId,token:x.data.readCredential}}

test('PUSH_ZONE_MUTATION_REQUIRES_SCOPE_CREDENTIAL',async()=>{const d=db(),a=await mkSub(d,'owner'),b=await mkSub(d,'other'),u=new URL(a.origin+'/api/push/zones');let r=await handlePush(new Request(u,{method:'POST',headers:{origin:a.origin,'content-type':'application/json'},body:JSON.stringify({subscriptionId:a.sid,readCredential:a.token,lat:-31.6,lon:-60.7,radiusKm:25})}),a.env,u),x=await r.json(),zoneId=x.data.zoneId;assert.equal(r.status,201);r=await handlePush(new Request(u,{method:'PUT',headers:{origin:a.origin,'content-type':'application/json'},body:JSON.stringify({subscriptionId:b.sid,readCredential:b.token,zoneId,lat:-32,lon:-61,radiusKm:25})}),a.env,u);assert.equal(r.status,403);assert.equal(d.raw.prepare('SELECT subscription_id FROM push_zones WHERE id=?').get(zoneId).subscription_id,a.sid)});
test('PUSH_CROSS_SUBSCRIPTION_MUTATION_REJECTED',async()=>{const d=db(),a=await mkSub(d,'owner2'),b=await mkSub(d,'other2'),u=new URL(a.origin+'/api/push/zones');let r=await handlePush(new Request(u,{method:'POST',headers:{origin:a.origin,'content-type':'application/json'},body:JSON.stringify({subscriptionId:a.sid,readCredential:a.token,lat:-31.6,lon:-60.7})}),a.env,u),x=await r.json(),zoneId=x.data.zoneId;r=await handlePush(new Request(u,{method:'DELETE',headers:{origin:a.origin,'content-type':'application/json'},body:JSON.stringify({subscriptionId:b.sid,readCredential:b.token,zoneId})}),a.env,u);assert.equal(r.status,403);assert.equal(Number(d.raw.prepare('SELECT COUNT(*) n FROM push_zones WHERE id=?').get(zoneId).n),1)});
test('PUSH_SUBSCRIPTION_MUTATION_REQUIRES_SCOPE_CREDENTIAL',async()=>{const d=db(),a=await mkSub(d,'sub-owner'),b=await mkSub(d,'sub-other'),u=new URL(a.origin+'/api/push/subscribe'),r=await handlePush(new Request(u,{method:'DELETE',headers:{origin:a.origin,'content-type':'application/json'},body:JSON.stringify({subscriptionId:a.sid,readCredential:b.token})}),a.env,u);assert.equal(r.status,403);assert.equal(Number(d.raw.prepare('SELECT COUNT(*) n FROM push_subscriptions WHERE id=?').get(a.sid).n),1)});
test('PUSH_410_CLEANUP_REFERENTIALLY_CLEAN',async()=>{const d=db(),a=await mkSub(d,'gone'),u=new URL(a.origin+'/api/push/zones'),zr=await handlePush(new Request(u,{method:'POST',headers:{origin:a.origin,'content-type':'application/json'},body:JSON.stringify({subscriptionId:a.sid,readCredential:a.token,lat:-31.6,lon:-60.7})}),a.env,u);assert.equal(zr.status,201);const rec={recordId:'smn:gone',sourceRole:'OFFICIAL_WARNING',lifecycle:'ACTIVE',publicMessage:true,capStatus:'Actual',capMsgType:'Alert',capIdentifier:'gone-1',bbox:[-60.8,-31.7,-60.6,-31.5],headline:'Gone',description:'x',hazardType:'STORM',expiresAt:'2026-08-28T23:00:00Z'},out=await dispatchRecordNotifications(rec,a.env,{sender:async()=>({ok:false,status:410,deleteSubscription:true})});assert.equal(out.deleted,1);for(const [t,c] of[['push_zones','subscription_id'],['notification_snapshots','subscription_id'],['notification_deliveries','subscription_id'],['push_read_credentials','subscription_id'],['push_subscriptions','id']])assert.equal(Number(d.raw.prepare(`SELECT COUNT(*) n FROM ${t} WHERE ${c}=?`).get(a.sid).n),0)});
test('PUSH_DELIVERY_BATCHING_BOUNDED',()=>assert.match(fs.readFileSync('src/worker/push.js','utf8'),/ORDER BY z\.created_at LIMIT 500/));
