
import test from'node:test';
import assert from'node:assert/strict';
import fs from'node:fs';
import {DatabaseSync} from'node:sqlite';
import {parseInpresHtml} from'../src/providers/inpres.js';
import {parseUsgsGeoJson} from'../src/providers/usgs.js';
import {parseEonetWildfires} from'../src/providers/eonet.js';
import {publicRecord,reconcile} from'../src/domain/hazard.js';
import {runDueJobs,scheduleDueProviders,finishJob,persistHazardEvents,CADENCE_SECONDS,projectedOperationsDay} from'../src/worker/ingestion.js';
import {handlePush,dispatchRecordNotifications,deliveryRevision} from'../src/worker/push.js';
import {SOURCE_REGISTRY} from'../src/providers/registry.js';

function db(){const raw=new DatabaseSync(':memory:');raw.exec(fs.readFileSync('migrations/0001-national.sql','utf8'));raw.exec(fs.readFileSync('migrations/0002-order031.sql','utf8'));raw.exec(fs.readFileSync('migrations/0003-worker-job-lease.sql','utf8'));return{raw,prepare(sql){let args=[];return{bind(...x){args=x;return this},async run(){const r=raw.prepare(sql).run(...args);return{meta:{changes:Number(r.changes||0)}}},async all(){return{results:raw.prepare(sql).all(...args)}},async first(){return raw.prepare(sql).get(...args)||null}}}}}
const NOW=Date.parse('2026-08-28T10:00:00Z');
const baseEvent={eventId:'event:STORM:x',hazardType:'STORM',lifecycle:'ACTIVE',recordIds:['r1'],geometry:null,bbox:[-61,-32,-60,-31],regions:['AR-S'],provinces:['Santa Fe'],displaySeverity:'Moderate',officialUrgency:'Expected',officialCertainty:'Likely',officialWarningState:'ACTIVE',observationState:'NONE',modelState:'NONE',impactState:'NONE',externalSignalState:'NONE',verificationState:'OFFICIAL_WARNING_ONLY',freshness:'FRESH',firstSeenAt:'2026-08-28T09:00:00Z',lastChangedAt:'2026-08-28T09:00:00Z',expiresAt:'2026-08-28T15:00:00Z',dominantHeadline:'Tormenta',plainLanguageSummary:'Prueba',recommendedActions:[],records:[]};

test('D1_BINDING_REQUIRED_FOR_CANONICAL_DURABLE_MODE',async()=>{await assert.rejects(()=>runDueJobs(null,async()=>({records:[]})),/D1_BINDING_REQUIRED/)});
test('SCHEDULER_IDEMPOTENT_BUCKETS',async()=>{const d=db();const a=await scheduleDueProviders(d,NOW),b=await scheduleDueProviders(d,NOW);assert.equal(a.length,Object.keys(CADENCE_SECONDS).length);assert.equal(b.length,0);assert.equal(Number(d.raw.prepare('SELECT COUNT(*) n FROM provider_jobs').get().n),a.length)});
test('JOB_RETRY_DEADLETTER_CIRCUIT',async()=>{const d=db();await scheduleDueProviders(d,NOW);const id=d.raw.prepare("SELECT id FROM provider_jobs WHERE provider_id='smn-cap'").get().id;d.raw.prepare("UPDATE provider_jobs SET status='RUNNING',attempts=4 WHERE id=?").run(id);await finishJob(d,id,'smn-cap',false,4,'FIXTURE_FAIL',{},NOW);const j=d.raw.prepare('SELECT status,attempts FROM provider_jobs WHERE id=?').get(id),p=d.raw.prepare("SELECT status,circuit_open_until FROM provider_registry WHERE provider_id='smn-cap'").get();assert.equal(j.status,'DEAD_LETTER');assert.equal(Number(j.attempts),5);assert.equal(p.status,'CIRCUIT_OPEN');assert.ok(p.circuit_open_until)});
test('EVENT_VERSION_ON_MATERIAL_CHANGE and EVENT_VERSION_NOOP_NO_DUPLICATE',async()=>{const d=db();await persistHazardEvents(d,[baseEvent],NOW);await persistHazardEvents(d,[baseEvent],NOW+1000);assert.equal(Number(d.raw.prepare('SELECT COUNT(*) n FROM event_versions').get().n),1);await persistHazardEvents(d,[{...baseEvent,displaySeverity:'Severe',officialUrgency:'Immediate'}],NOW+2000);assert.equal(Number(d.raw.prepare('SELECT COUNT(*) n FROM event_versions').get().n),2)});
test('STALE_RECORD_NOT_CURRENT_EVENT',()=>{const r=publicRecord({recordId:'r',providerId:'x',providerRecordId:'1',hazardType:'FLOOD',sourceRole:'OFFICIAL_LOCAL_OR_NATIONAL_OBSERVATION',sourceOrganization:'X',official:true,issuedAt:'2026-08-20T00:00:00Z',observedAt:'2026-08-20T00:00:00Z',effectiveAt:null,onsetAt:null,expiresAt:null,fetchedAt:'2026-08-20T00:01:00Z',freshness:'STALE',verificationState:'VERIFIED',geometry:null,bbox:[-61,-32,-60,-31],regionCodes:['AR-S'],headline:'Viejo',description:'',instruction:null,sourceUrl:'https://example.invalid',attribution:'X',rawHash:'x',lifecycle:'ACTIVE'});assert.equal(reconcile([r],new Date(NOW)).length,0)});
test('REGION_CODE_ALONE_NOT_EVENT_MERGE',()=>{const mk=(id,bbox)=>publicRecord({recordId:id,providerId:'smn-cap',providerRecordId:id,hazardType:'STORM',sourceRole:'OFFICIAL_WARNING',sourceOrganization:'SMN',official:true,issuedAt:'2026-08-28T09:00:00Z',observedAt:null,effectiveAt:null,onsetAt:null,expiresAt:'2026-08-28T14:00:00Z',fetchedAt:'2026-08-28T09:01:00Z',freshness:'FRESH',verificationState:'VERIFIED_MACHINE',geometry:null,bbox,regionCodes:['AR-S'],province:'Santa Fe',headline:id,description:'',instruction:null,sourceUrl:'https://smn.gob.ar',attribution:'SMN',rawHash:id,lifecycle:'ACTIVE'});assert.equal(reconcile([mk('a',[-60.8,-31.8,-60.6,-31.6]),mk('b',[-61.9,-30.6,-61.7,-30.4])],new Date(NOW)).length,2)});
test('INPRES_STRICT_PARSE',()=>{const x=parseInpresHtml(fs.readFileSync('test/fixtures/inpres-real-fragment.html','utf8'),{fetchedAt:'2026-08-28T10:00:00Z'});assert.equal(x.records.length,2);assert.equal(x.records[0].observedAt,'2026-08-28T09:07:02.000Z');assert.equal(x.records[0].magnitude,2.8);assert.equal(x.records[0].depthKm,121);assert.equal(x.records[0].intensity,null);assert.equal(x.records[1].intensity,'II a III')});
test('INPRES_SCHEMA_DRIFT_FAIL_CLOSED',()=>assert.throws(()=>parseInpresHtml(fs.readFileSync('test/fixtures/inpres-drift.html','utf8')),/INPRES_SCHEMA_DRIFT/));
test('INPRES_FUTURE_TIMESTAMP_REJECT',()=>{const x=parseInpresHtml(fs.readFileSync('test/fixtures/inpres-real-fragment.html','utf8'),{fetchedAt:'2026-08-28T05:00:00Z'});assert.equal(x.records[0].verificationState,'FUTURE_REJECTED')});
test('USGS_SUPPLEMENTARY_NOT_ARGENTINE_OFFICIAL',()=>{const x=parseUsgsGeoJson({type:'FeatureCollection',metadata:{count:1},features:[{type:'Feature',id:'u1',geometry:{type:'Point',coordinates:[-69,-31,10]},properties:{time:NOW-60000,mag:3.2,status:'reviewed',place:'San Juan',url:'https://earthquake.usgs.gov/earthquakes/eventpage/u1'}}]},{fetchedAt:new Date(NOW).toISOString()});assert.equal(x.records[0].sourceRole,'SUPPLEMENTARY_EXTERNAL_OBSERVATION');assert.equal(x.records[0].official,false)});
test('EARTHQUAKE_INPRES_USGS_DEDUPE',()=>{const i=parseInpresHtml(fs.readFileSync('test/fixtures/inpres-real-fragment.html','utf8'),{fetchedAt:'2026-08-28T10:00:00Z'}).records[0],u=parseUsgsGeoJson({type:'FeatureCollection',metadata:{count:1},features:[{type:'Feature',id:'u',geometry:{type:'Point',coordinates:[-69.21,-31.94,120]},properties:{time:Date.parse(i.observedAt)+30000,mag:2.9,status:'reviewed',place:'San Juan',url:'https://earthquake.usgs.gov/earthquakes/eventpage/u'}}]},{fetchedAt:'2026-08-28T10:00:00Z'}).records[0];const e=reconcile([i,u],new Date(NOW));assert.equal(e.length,1);assert.equal(e[0].sourceCount,2)});
test('EONET_SUPPLEMENTARY_ONLY',()=>{const x=parseEonetWildfires({events:[{id:'E1',title:'Wildfire',categories:[{id:'wildfires',title:'Wildfires'}],geometry:[{date:'2026-08-28T09:00:00Z',type:'Point',coordinates:[-60,-31]}],sources:[{url:'https://eonet.gsfc.nasa.gov/'}]}]},{fetchedAt:'2026-08-28T10:00:00Z'});assert.equal(x.records.length,1);assert.equal(x.records[0].sourceRole,'SUPPLEMENTARY_EXTERNAL_EVENT_SIGNAL');assert.equal(x.records[0].official,false)});
test('NASA_GPM_COVERAGE_TRUTH',()=>{assert.equal(SOURCE_REGISTRY.find(x=>x.providerId==='nasa-gpm').coverage,'SANTA_FE_POINT_SPECIALIST');assert.equal(SOURCE_REGISTRY.find(x=>x.providerId==='google-flood').status,'BLOCKED_EXTERNAL_APPROVAL_OR_CREDENTIAL')});
test('SERVICE_WORKER_RELEASE_CACHE_KEY',()=>{const sw=fs.readFileSync('public/service-worker.js','utf8');assert.match(sw,/sos-sf-shell-\$\{RELEASE\}/);assert.match(sw,/keys\.filter\(key=>key\.startsWith\('sos-sf-'\).*key\.endsWith\(RELEASE\)/s);assert.doesNotMatch(sw,/ORDER030-PREFREEZE/)});
test('PWA_MANIFEST_ICONS',()=>{const m=JSON.parse(fs.readFileSync('public/manifest.webmanifest','utf8'));assert.equal(m.id,'/');assert.equal(m.scope,'/');assert.equal(m.display,'standalone');for(const [f,w] of [['public/icons/icon-192.png',192],['public/icons/icon-512.png',512],['public/icons/icon-maskable-512.png',512]]){const b=fs.readFileSync(f);assert.equal(b.toString('hex',0,8),'89504e470d0a1a0a');assert.equal(b.readUInt32BE(16),w);assert.equal(b.readUInt32BE(20),w)}assert.ok(m.icons.some(x=>x.sizes==='512x512'&&x.purpose==='maskable'))});
test('PUSH_CONFIG_ENABLED_WITH_RUNTIME',async()=>{const u=new URL('https://sos-sf.simondalmasso44.workers.dev/api/push/config'),r=await handlePush(new Request(u),{HAZARD_DB:{},VAPID_PUBLIC_KEY:'AAA',VAPID_PRIVATE_JWK:'{}',PUSH_STORAGE_KEY:'x'.repeat(32)},u),x=await r.json();assert.equal(x.data.enabled,true)});
test('PUSH_GENERIC_FALLBACK and PUSH_TEST_NEVER_CREATES_HAZARD',()=>{const sw=fs.readFileSync('public/service-worker.js','utf8'),push=fs.readFileSync('src/worker/push.js','utf8');assert.match(sw,/catch\{n=generic\(\)\}/);assert.match(sw,/No se pudo recuperar el detalle del aviso/);const a=push.indexOf("u.pathname==='/api/push/test'"),b=push.indexOf("return safeErr('METHOD_NOT_ALLOWED'",a);assert.doesNotMatch(push.slice(a,b),/hazard_records|hazard_events/)});
test('PUSH_EVENT_SPECIFIC_NOTIFICATION',async()=>{const d=db(),env={HAZARD_DB:d,PUSH_STORAGE_KEY:'x'.repeat(32),VAPID_PUBLIC_KEY:'AAA',VAPID_PRIVATE_JWK:'{}'},origin='https://sos-sf.simondalmasso44.workers.dev',endpoint='https://fcm.googleapis.com/fcm/send/order031-event';let u=new URL(origin+'/api/push/subscribe'),r=await handlePush(new Request(u,{method:'POST',headers:{origin,'content-type':'application/json'},body:JSON.stringify({endpoint,keys:{p256dh:'a'.repeat(32),auth:'b'.repeat(16)}})}),env,u),x=await r.json(),sid=x.data.subscriptionId,token=x.data.readCredential;u=new URL(origin+'/api/push/zones');r=await handlePush(new Request(u,{method:'POST',headers:{origin,'content-type':'application/json'},body:JSON.stringify({subscriptionId:sid,readCredential:token,lat:-31.6,lon:-60.7,radiusKm:25})}),env,u);assert.equal(r.status,201);const rec={recordId:'smn:1',sourceRole:'OFFICIAL_WARNING',lifecycle:'ACTIVE',publicMessage:true,capStatus:'Actual',capMsgType:'Alert',capIdentifier:'warn-1',bbox:[-60.8,-31.7,-60.6,-31.5],headline:'Tormenta oficial',description:'Detalle oficial',hazardType:'STORM',expiresAt:'2026-08-28T15:00:00Z'},sender=async()=>({ok:true,status:201,deleteSubscription:false});assert.equal((await dispatchRecordNotifications(rec,env,{sender})).sent,1);const a=d.raw.prepare("SELECT title,deep_link_path,notification_tag FROM notification_snapshots WHERE kind='ALERT'").get();assert.match(a.title,/Tormenta oficial/);assert.match(a.deep_link_path,/event=/);await dispatchRecordNotifications({...rec,capMsgType:'Update',capSeverity:'Severe'},env,{sender});assert.equal(d.raw.prepare("SELECT DISTINCT notification_tag FROM notification_snapshots WHERE event_id='warn-1'").all().length,1);assert.notEqual(deliveryRevision(rec),deliveryRevision({...rec,capMsgType:'Update',capSeverity:'Severe'}))});
test('COST_BUDGET_ORDER031',()=>{const c=projectedOperationsDay();assert.equal(c.queueOps,0);assert.ok(c.workerRequests<100000);assert.ok(c.d1Writes<100000);assert.equal('ign-risk'in CADENCE_SECONDS,false)});
