import test from 'node:test';
import assert from 'node:assert/strict';
import {canonicalObservation,observationDistanceKm,rankNearbyEvidence,clusterPresentationEvents} from '../src/domain/observation.js';
import {normalizeInaSeriesGeoJson,riverObservationsFromSnapshot} from '../src/providers/ina-observations.js';
const REF={lat:-31.6333,lon:-60.7000};
const NOW='2026-09-07T03:00:00.000Z';
const meta={type:'FeatureCollection',features:[
 {type:'Feature',geometry:{type:'Point',coordinates:[-60.684,-31.659]},properties:{id:30,nombre:'Altura hidrométrica',estacion:{id:30,nombre:'Santa Fe',rio:'Río Paraná'}}},
 {type:'Feature',geometry:{type:'Point',coordinates:[-60.773,-31.667]},properties:{id:3044,nombre:'Altura hidrométrica',estacion:{id:1679,nombre:'Santo Tomé',rio:'Río Salado'}}},
]};
const snapshot={generatedAt:NOW,systems:[
 {id:'parana-santa-fe',stationCode:'30',sourceId:'ina-rest-30',watercourse:'Río Paraná',stationName:'Santa Fe',available:true,currentMetres:2.65,delta24h:-0.05,trend:'FALLING',observedAt:'2026-09-07T02:00:00.000Z',fetchedAt:NOW,freshness:'FRESH'},
 {id:'salado-santo-tome',stationCode:'1679',sourceId:'ina-rest-3044',watercourse:'Río Salado',stationName:'Santo Tomé',available:true,currentMetres:3.42,delta24h:0.08,trend:'RISING',observedAt:'2026-09-06T20:00:00.000Z',fetchedAt:NOW,freshness:'FRESH'},
]};
test('GENERIC_OBSERVATION_CONTRACT_PRESERVES_ROLE_NULLS_AND_GEOMETRY',()=>{const o=canonicalObservation({observationId:'obs:1',observationType:'RIVER_LEVEL',hazardType:'FLOOD',providerId:'ina',sourceOrganization:'Instituto Nacional del Agua',sourceRole:'OFFICIAL_LOCAL_OR_NATIONAL_OBSERVATION',label:'Río Paraná',locationLabel:'Santa Fe',geometry:{type:'Point',coordinates:[-60.684,-31.659]},geometryPrecision:'PROVIDER_PUBLISHED',observedAt:NOW,fetchedAt:NOW,freshness:'FRESH',verificationState:'PUBLISHED_OPERATIONAL',value:null,unit:'m',delta24h:null,trend:'UNKNOWN'});assert.equal(o.value,null);assert.equal(o.delta24h,null);assert.equal(o.severity,undefined);assert.deepEqual(o.geometry.coordinates,[-60.684,-31.659])});
test('INA_SERIES_METADATA_NORMALIZES_REAL_POINT_GEOMETRY_WITH_PROVENANCE',()=>{const rows=normalizeInaSeriesGeoJson(meta);assert.equal(rows.length,2);assert.deepEqual(rows[0].geometry,{type:'Point',coordinates:[-60.684,-31.659]});assert.equal(rows[0].coordinateSource,'INA_SIYAH_SERIES_GEOJSON');assert.equal(rows[1].stationId,'1679');assert.equal(rows[1].seriesId,'3044')});
test('RIVER_MEASUREMENT_NEVER_ALERT',()=>{const obs=riverObservationsFromSnapshot(snapshot,normalizeInaSeriesGeoJson(meta),Date.parse(NOW));assert.equal(obs.length,2);for(const o of obs){assert.equal(o.observationType,'RIVER_LEVEL');assert.equal(o.sourceRole,'OFFICIAL_LOCAL_OR_NATIONAL_OBSERVATION');assert.equal(o.severity,undefined);assert.equal(o.isWarning,false)}});
test('RIVER_LEVEL_DELTA_FRESHNESS_SOURCE_AND_GEOMETRY_PRESERVED',()=>{const[o]=riverObservationsFromSnapshot(snapshot,normalizeInaSeriesGeoJson(meta),Date.parse(NOW));assert.equal(o.value,2.65);assert.equal(o.delta24h,-0.05);assert.equal(o.freshness,'FRESH');assert.equal(o.providerId,'ina');assert.equal(o.unit,'m');assert.equal(o.lat,-31.659);assert.equal(o.lon,-60.684)});
test('UNKNOWN_RIVER_LEVEL_NEVER_ZERO',()=>{const s=structuredClone(snapshot);s.systems[0].currentMetres=null;s.systems[0].available=false;const[o]=riverObservationsFromSnapshot(s,normalizeInaSeriesGeoJson(meta),Date.parse(NOW));assert.equal(o.value,null);assert.notEqual(o.value,0)});
test('STALE_RIVER_NEVER_CURRENT',()=>{const s=structuredClone(snapshot);s.systems[0].freshness='STALE';s.systems[0].observedAt='2026-09-05T00:00:00.000Z';const[o]=riverObservationsFromSnapshot(s,normalizeInaSeriesGeoJson(meta),Date.parse(NOW));assert.equal(o.freshness,'STALE');assert.equal(o.isCurrent,false)});
test('NO_FAKE_DISTANCE_WITHOUT_GEOMETRY',()=>{const o=canonicalObservation({observationId:'obs:no-geo',observationType:'RIVER_LEVEL',providerId:'ina',sourceOrganization:'INA',sourceRole:'OFFICIAL_LOCAL_OR_NATIONAL_OBSERVATION',label:'Río',observedAt:NOW,fetchedAt:NOW,freshness:'FRESH',verificationState:'PUBLISHED_OPERATIONAL',value:1,unit:'m'});assert.equal(observationDistanceKm(REF,o),null)});
test('NEARBY_RIVERS_SORT_BY_DISTANCE',()=>{const obs=riverObservationsFromSnapshot(snapshot,normalizeInaSeriesGeoJson(meta),Date.parse(NOW)),ranked=rankNearbyEvidence(REF,[],obs);assert.equal(ranked.length,2);assert.ok(ranked[0].distanceKm<=ranked[1].distanceKm)});
test('CROSS_PROVINCE_NEARBY_RIVER_NOT_HIDDEN',()=>{const obs=riverObservationsFromSnapshot(snapshot,normalizeInaSeriesGeoJson(meta),Date.parse(NOW)).map((o,i)=>({...o,province:i?'Entre Ríos':'Santa Fe'})),ranked=rankNearbyEvidence(REF,[],obs);assert.equal(ranked.length,2)});
test('WARNING_AND_RIVER_CAN_COEXIST_ROLE_SEMANTICS_PRESERVED',()=>{const warning={eventId:'event:STORM:a',hazardType:'STORM',sourceRole:'OFFICIAL_WARNING',displaySeverity:'Severe',freshness:'FRESH',geometry:{type:'Point',coordinates:[-60.7,-31.64]},dominantHeadline:'Tormenta'},obs=riverObservationsFromSnapshot(snapshot,normalizeInaSeriesGeoJson(meta),Date.parse(NOW)),ranked=rankNearbyEvidence(REF,[warning],obs);assert.equal(ranked.length,3);assert.equal(ranked.filter(x=>x.evidenceKind==='WARNING').length,1);assert.equal(ranked.filter(x=>x.evidenceKind==='OBSERVATION').length,2)});
test('DETERMINISTIC_NEARBY_RANKING',()=>{const obs=riverObservationsFromSnapshot(snapshot,normalizeInaSeriesGeoJson(meta),Date.parse(NOW)),a=rankNearbyEvidence(REF,[],obs).map(x=>x.id),b=rankNearbyEvidence(REF,[],[...obs].reverse()).map(x=>x.id);assert.deepEqual(a,b)});
test('PRESENTATION_CLUSTER_PRESERVES_EVENT_IDS',()=>{const base={hazardType:'WIND',displaySeverity:'Moderate',dominantHeadline:'Viento fuerte',firstSeenAt:'2026-09-07T00:00:00Z',lastChangedAt:'2026-09-07T01:00:00Z',expiresAt:'2026-09-07T08:00:00Z',sources:[{providerId:'smn-cap',sourceRole:'OFFICIAL_WARNING'}]},out=clusterPresentationEvents([{...base,eventId:'e1'},{...base,eventId:'e2',dominantHeadline:'Viento  fuerte'}]);assert.equal(out.length,1);assert.deepEqual(out[0].eventIds,['e1','e2'])});
test('DISTINCT_SEVERITY_SOURCE_AND_HAZARD_NOT_CLUSTERED',()=>{const base={eventId:'e1',hazardType:'WIND',displaySeverity:'Moderate',dominantHeadline:'Viento fuerte',firstSeenAt:'2026-09-07T00:00:00Z',expiresAt:'2026-09-07T08:00:00Z',sources:[{providerId:'smn-cap',sourceRole:'OFFICIAL_WARNING'}]};assert.equal(clusterPresentationEvents([base,{...base,eventId:'e2',displaySeverity:'Severe'}]).length,2);assert.equal(clusterPresentationEvents([base,{...base,eventId:'e2',sources:[{providerId:'other'}]}]).length,2);assert.equal(clusterPresentationEvents([base,{...base,eventId:'e2',hazardType:'STORM'}]).length,2)});

test('OBSERVATION_EVENTS_NOT_PRESENTATION_CLUSTERED',()=>{const base={hazardType:'FLOOD',displaySeverity:null,dominantHeadline:'Nivel observado',firstSeenAt:'2026-09-07T00:00:00Z',expiresAt:'2026-09-07T08:00:00Z',sources:[{providerId:'ina',sourceRole:'OFFICIAL_LOCAL_OR_NATIONAL_OBSERVATION'}]};const out=clusterPresentationEvents([{...base,eventId:'o1'},{...base,eventId:'o2'}]);assert.equal(out.length,2);assert.deepEqual(out.map(x=>x.eventIds),[['o1'],['o2']])});

test('EARTHQUAKE_AND_RIVER_CAN_COEXIST_WITH_ROLE_SEMANTICS',()=>{const quake={eventId:'event:EARTHQUAKE:q1',hazardType:'EARTHQUAKE',sourceRole:'OFFICIAL_LOCAL_OR_NATIONAL_OBSERVATION',freshness:'FRESH',geometry:{type:'Point',coordinates:[-60.72,-31.64]},dominantHeadline:'Sismo observado',observedAt:NOW},obs=riverObservationsFromSnapshot(snapshot,normalizeInaSeriesGeoJson(meta),Date.parse(NOW)),ranked=rankNearbyEvidence(REF,[quake],obs);assert.equal(ranked.length,3);const q=ranked.find(x=>x.id===quake.eventId);assert.equal(q.evidenceKind,'OBSERVATION');assert.equal(q.sourceRole,'OFFICIAL_LOCAL_OR_NATIONAL_OBSERVATION');assert.equal(q.severity,null)});
