import test from'node:test';import assert from'node:assert/strict';import{dispatchRecordNotifications}from'../src/worker/push.js';
const secret='0123456789abcdef0123456789abcdef';
const b64u=b=>Buffer.from(b).toString('base64url');
async function seal(v){const iv=new Uint8Array(12),key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'AES-GCM'},false,['encrypt']);const ct=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},key,new TextEncoder().encode(v)));return`${b64u(iv)}.${b64u(ct)}`}
class DB{constructor(rows){this.rows=rows;this.deliveries=new Map;this.deletedSubs=new Set;this.deletedZones=new Set}prepare(sql){const db=this;let a=[];return{bind(...x){a=x;return this},async all(){return{results:sql.startsWith('SELECT z.*')?db.rows.filter(r=>!db.deletedSubs.has(r.subscription_id)):[]}},async first(){if(sql.startsWith('SELECT id FROM notification_deliveries')){const[sub,event,status]=a;for(const[id,d]of db.deliveries)if(d.subscription_id===sub&&d.event_id===event&&d.status===status)return{id}}return null},async run(){if(sql.startsWith('INSERT OR IGNORE INTO notification_deliveries')){const[id,subscription_id,event_id,warning_revision,status,created_at]=a;if(db.deliveries.has(id))return{meta:{changes:0}};db.deliveries.set(id,{subscription_id,event_id,warning_revision,status,created_at});return{meta:{changes:1}}}if(sql.startsWith('UPDATE notification_deliveries SET status=?')){const[status,id]=a;db.deliveries.get(id).status=status;return{meta:{changes:1}}}if(sql.includes("status='ENDPOINT_GONE'")){const[id]=a;db.deliveries.get(id).status='ENDPOINT_GONE';return{meta:{changes:1}}}if(sql.startsWith('DELETE FROM push_zones')){db.deletedZones.add(a[0]);return{meta:{changes:1}}}if(sql.startsWith('DELETE FROM push_subscriptions')){db.deletedSubs.add(a[0]);return{meta:{changes:1}}}return{meta:{changes:1}}}}}}
const base={recordId:'warning:1',sourceRole:'OFFICIAL_WARNING',lifecycle:'ACTIVE',capStatus:'Actual',bbox:[-60.8,-31.7,-60.6,-31.5],capIdentifier:'warn1',capMsgType:'Alert',capSeverity:'Moderate',headline:'Alerta',expiresAt:'2026-08-29T00:00:00Z'};
async function row(){return{subscription_id:'sub1',lat:-31.63,lon:-60.7,radius_km:25,official_warnings:1,model_signals:0,satellite_estimates:0,endpoint:await seal('https://fcm.googleapis.com/fcm/send/test')}}
const env=db=>({HAZARD_DB:db,PUSH_STORAGE_KEY:secret,VAPID_PUBLIC_KEY:'test',VAPID_PRIVATE_JWK:'{}'});
test('PUSH_DEDUPE_UPDATE_CANCEL',async()=>{const db=new DB([await row()]);let sends=0;const sender=async()=>{sends++;return{ok:true,status:201,deleteSubscription:false}};let r=await dispatchRecordNotifications(base,env(db),{sender});assert.equal(r.sent,1);r=await dispatchRecordNotifications(base,env(db),{sender});assert.equal(r.sent,0);assert.equal(r.skipped,1);assert.equal(sends,1);r=await dispatchRecordNotifications({...base,capMsgType:'Update',capSeverity:'Severe'},env(db),{sender});assert.equal(r.sent,1);assert.equal(sends,2);r=await dispatchRecordNotifications({...base,recordId:'cancel:1',capMsgType:'Cancel',capReferences:[{identifier:'warn1'}]},env(db),{sender});assert.equal(r.sent,1);assert.equal(sends,3)});
test('PUSH_410_DELETES_SUBSCRIPTION',async()=>{const db=new DB([await row()]);const r=await dispatchRecordNotifications(base,env(db),{sender:async()=>({ok:false,status:410,deleteSubscription:true})});assert.equal(r.deleted,1);assert.equal(db.deletedSubs.has('sub1'),true);assert.equal(db.deletedZones.has('sub1'),true);assert.equal([...db.deliveries.values()][0].status,'ENDPOINT_GONE')});
