import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import{DatabaseSync}from'node:sqlite';
import{scheduleDueProviders,claimDueJobs,recoverStuckJobs,MAX_RUNTIME_RECOVERIES,WORKER_LEASE_EXPIRY}from'../src/worker/ingestion.js';
function db(){const raw=new DatabaseSync(':memory:');for(const f of['migrations/0001-national.sql','migrations/0002-order031.sql','migrations/0003-worker-job-lease.sql'])raw.exec(fs.readFileSync(f,'utf8'));return{raw,prepare(sql){let args=[];return{bind(...x){args=x;return this},async run(){const r=raw.prepare(sql).run(...args);return{meta:{changes:Number(r.changes||0)}}},async all(){return{results:raw.prepare(sql).all(...args)}},async first(){return raw.prepare(sql).get(...args)||null}}}}}
const T=Date.parse('2026-08-28T12:00:00Z');
test('NEW_BUCKET_BLOCKED_BY_NONTERMINAL_PROVIDER_JOB',async()=>{const d=db();await scheduleDueProviders(d,T);await claimDueJobs(d,new Date(T).toISOString());d.raw.prepare("UPDATE provider_registry SET next_due_at=? WHERE provider_id='smn-cap'").run(new Date(T+300000).toISOString());const x=await scheduleDueProviders(d,T+300000);assert.equal(x.some(id=>id.startsWith('smn-cap:')),false);assert.equal(Number(d.raw.prepare("SELECT COUNT(*) n FROM provider_jobs WHERE provider_id='smn-cap'").get().n),1)});
test('RUNNING_LEASE_USES_CLAIM_TIME_NOT_CREATED_TIME',async()=>{const d=db(),created=new Date(T-86400000).toISOString(),due=new Date(T).toISOString();d.raw.prepare("INSERT INTO provider_jobs(id,provider_id,status,attempts,next_attempt_at,created_at,runtime_recovery_count) VALUES('j','smn-cap','PENDING',0,?,?,0)").run(due,created);const[j]=await claimDueJobs(d,due);const r=d.raw.prepare("SELECT created_at,claimed_at,lease_expires_at FROM provider_jobs WHERE id='j'").get();assert.equal(r.created_at,created);assert.equal(r.claimed_at,due);assert.equal(j.claimed_at,due);assert.ok(Date.parse(r.lease_expires_at)>T)});
test('STUCK_RUNNING_RECOVERS_ONCE',async()=>{const d=db(),past=new Date(T-1).toISOString();d.raw.prepare("INSERT INTO provider_jobs(id,provider_id,status,attempts,next_attempt_at,created_at,claimed_at,lease_expires_at,runtime_recovery_count) VALUES('j','smn-cap','RUNNING',0,?,?,?,?,0)").run(new Date(T-10000).toISOString(),new Date(T-20000).toISOString(),new Date(T-10000).toISOString(),past);assert.deepEqual(await recoverStuckJobs(d,T),{recovered:1,bounded:0});assert.deepEqual(await recoverStuckJobs(d,T),{recovered:0,bounded:0});const r=d.raw.prepare("SELECT status,last_error,runtime_recovery_count,claimed_at,lease_expires_at FROM provider_jobs WHERE id='j'").get();assert.equal(r.status,'RETRY');assert.equal(r.last_error,WORKER_LEASE_EXPIRY);assert.equal(Number(r.runtime_recovery_count),1);assert.equal(r.claimed_at,null);assert.equal(r.lease_expires_at,null)});
test('REPEATED_RUNTIME_LEASE_EXPIRY_BOUNDED',async()=>{const d=db(),past=new Date(T-1).toISOString();d.raw.prepare("INSERT INTO provider_jobs(id,provider_id,status,attempts,next_attempt_at,created_at,claimed_at,lease_expires_at,runtime_recovery_count) VALUES('j','smn-cap','RUNNING',0,?,?,?,?,?)").run(new Date(T-10000).toISOString(),new Date(T-20000).toISOString(),new Date(T-10000).toISOString(),past,MAX_RUNTIME_RECOVERIES);assert.deepEqual(await recoverStuckJobs(d,T),{recovered:0,bounded:1});const r=d.raw.prepare("SELECT status,last_error,runtime_recovery_count FROM provider_jobs WHERE id='j'").get();assert.equal(r.status,'DEAD_LETTER');assert.equal(r.last_error,'WORKER_LEASE_EXPIRED_BOUNDED');assert.equal(Number(r.runtime_recovery_count),MAX_RUNTIME_RECOVERIES)});
test('PROVIDER_CIRCUIT_NOT_OPENED_BY_WORKER_LEASE_EXPIRY',async()=>{const d=db(),past=new Date(T-1).toISOString();d.raw.prepare("INSERT INTO provider_registry(provider_id,next_due_at,refresh_seconds,failure_count,status) VALUES('smn-cap',?,300,0,'FRESH')").run(new Date(T).toISOString());d.raw.prepare("INSERT INTO provider_jobs(id,provider_id,status,attempts,next_attempt_at,created_at,claimed_at,lease_expires_at,runtime_recovery_count) VALUES('j','smn-cap','RUNNING',0,?,?,?,?,0)").run(new Date(T-10000).toISOString(),new Date(T-20000).toISOString(),new Date(T-10000).toISOString(),past);await recoverStuckJobs(d,T);const p=d.raw.prepare("SELECT failure_count,circuit_open_until,error_class,status FROM provider_registry WHERE provider_id='smn-cap'").get();assert.equal(Number(p.failure_count),0);assert.equal(p.circuit_open_until,null);assert.equal(p.error_class,null);assert.equal(p.status,'FRESH')});
