import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import{DatabaseSync}from'node:sqlite';
import{parseCap,SMN_CAP_SENT_OFFSET_ANOMALY,}from'../src/providers/cap.js';import{smnFeed}from'../src/worker/national.js';import{persistHazardRecords,persistProviderVerification}from'../src/worker/ingestion.js';
const NOW='2026-08-28T11:10:00.000Z';
const cap=(id='a',sent='2026-08-28T10:52:07-03:00')=>`<alert><identifier>${id}</identifier><sender>smn@smn.gob.ar</sender><sent>${sent}</sent><status>Actual</status><msgType>Alert</msgType><scope>Public</scope><info><category>Met</category><event>Tormentas</event><urgency>Immediate</urgency><severity>Severe</severity><certainty>Likely</certainty><onset>2026-08-29T15:00:00-03:00</onset><expires>2026-08-29T20:59:59-03:00</expires><headline>Alerta ${id}</headline><area><areaDesc>Área</areaDesc><polygon>-31,-61 -31,-60 -32,-60 -31,-61</polygon></area></info></alert>`;
function db(){const raw=new DatabaseSync(':memory:');for(const f of['migrations/0001-national.sql','migrations/0002-order031.sql'])raw.exec(fs.readFileSync(f,'utf8'));return{raw,prepare(sql){let a=[];return{bind(...x){a=x;return this},async run(){const r=raw.prepare(sql).run(...a);return{meta:{changes:Number(r.changes||0)}}},async all(){return{results:raw.prepare(sql).all(...a)}},async first(){return raw.prepare(sql).get(...a)||null}}}}}
const rss=(n,pub='Fri, 28 Aug 2026 11:00:01 GMT')=>`<rss><channel>${Array.from({length:n},(_,i)=>`<item><title>x</title><link>https://ssl.smn.gob.ar/feeds/CAP/xml_generados/test_${i}.xml</link><description>x</description><pubDate>${pub}</pubDate></item>`).join('')}</channel></rss>`;
async function mock(feed,fn){const old=globalThis.fetch;globalThis.fetch=async x=>{const u=String(x);if(u.includes('rss_alertaCAP'))return new Response(feed,{headers:{'content-type':'application/rss+xml'}});const m=u.match(/test_(\d+)\.xml/);if(m)return new Response(cap(`id-${m[1]}`),{headers:{'content-type':'application/xml'}});throw Error('bad fetch')};try{return await fn()}finally{globalThis.fetch=old}}
test('SMN_SENT_OFFSET_ANOMALY_RSS_PUBDATE_RECONCILED',()=>{const r=parseCap(cap(),{sourceUrl:'https://ssl.smn.gob.ar/feeds/CAP/xml_generados/test.xml',fetchedAt:NOW,rssPubDate:'Fri, 28 Aug 2026 11:00:01 GMT'});assert.equal(r.timestampAnomaly,SMN_CAP_SENT_OFFSET_ANOMALY);assert.equal(r.timestampBasis,'RSS_PUBDATE_RECONCILED');assert.equal(r.effectivePublicationAt,'2026-08-28T11:00:01.000Z');assert.equal(r.freshness,'FRESH');assert.equal(r.verificationState,'VERIFIED_MACHINE_TIMESTAMP_RECONCILED')});
test('SMN_RAW_SENT_PRESERVED',()=>{const r=parseCap(cap(),{sourceUrl:'https://ssl.smn.gob.ar/feeds/CAP/xml_generados/test.xml',fetchedAt:NOW,rssPubDate:'Fri, 28 Aug 2026 11:00:01 GMT'});assert.equal(r.capSentRaw,'2026-08-28T10:52:07-03:00');assert.equal(r.capSentParsedAt,'2026-08-28T13:52:07.000Z');assert.equal(r.issuedAt,r.capSentParsedAt)});
test('SMN_ONSET_EXPIRES_NOT_SHIFTED',()=>{const r=parseCap(cap(),{sourceUrl:'https://ssl.smn.gob.ar/feeds/CAP/xml_generados/test.xml',fetchedAt:NOW,rssPubDate:'Fri, 28 Aug 2026 11:00:01 GMT'});assert.equal(r.onsetAt,'2026-08-29T18:00:00.000Z');assert.equal(r.expiresAt,'2026-08-29T23:59:59.000Z');assert.equal(r.effectiveAt,null);assert.equal(r.effectivePublicationAt,'2026-08-28T11:00:01.000Z')});
test('SMN_FUTURE_WITHOUT_SANE_RSS_FAILS_CLOSED',()=>{const r=parseCap(cap(),{sourceUrl:'https://ssl.smn.gob.ar/feeds/CAP/xml_generados/test.xml',fetchedAt:NOW,rssPubDate:'Fri, 28 Aug 2026 18:00:01 GMT'});assert.equal(r.freshness,'FUTURE_REJECTED');assert.equal(r.verificationState,'DEGRADED_TIMESTAMP_ANOMALY');assert.equal(r.timestampBasis,'CAP_SENT_UNRECONCILED');assert.equal(r.effectivePublicationAt,null)});
test('SMN_ALL_PUBLIC_ITEMS_FUTURE_REJECTED_NEVER_FRESH_NO_ALERTS',async()=>mock(rss(2,'Fri, 28 Aug 2026 18:00:01 GMT'),async()=>{const x=await smnFeed({},new Date(NOW),null);assert.equal(x.verification.state,'DEGRADED_TIMESTAMP_ANOMALY');assert.equal(x.verification.activeCount,null);assert.equal(x.verification.canSayNoActiveOfficialWarnings,false);assert.equal(x.records.every(r=>r.verificationState==='DEGRADED_TIMESTAMP_ANOMALY'),true)}));
test('SMN_PARTIAL_SCAN_CANNOT_REUSE_FRESH_VERIFICATION',async()=>{const d=db();d.raw.prepare("INSERT INTO runtime_state(key,payload_json,updated_at) VALUES('smn:scan',?,?)").run(JSON.stringify({feedHash:'old',cursor:21,completed:true}),'2026-08-28T10:00:00Z');d.raw.prepare("INSERT INTO provider_verification(provider_id,state,verified_at,active_count,can_say_no_active,parse_failures,feed_item_count,error_class,payload_json,updated_at) VALUES('smn-cap','FRESH_PARSED',?,0,1,0,21,NULL,?,?)").run('2026-08-28T10:00:00Z',JSON.stringify({feedHash:'old',scanCompleted:true}),'2026-08-28T10:00:00Z');await mock(rss(21),async()=>{const x=await smnFeed({HAZARD_DB:d},new Date(NOW),d);assert.equal(x.verification.state,'DEGRADED_PARTIAL_FEED');assert.equal(x.verification.activeCount,null);assert.equal(x.verification.canSayNoActiveOfficialWarnings,false);const pv=d.raw.prepare("SELECT state,active_count,can_say_no_active,payload_json FROM provider_verification WHERE provider_id='smn-cap'").get();assert.equal(pv.state,'DEGRADED_PARTIAL_FEED');assert.equal(pv.active_count,null);assert.equal(Number(pv.can_say_no_active),0);assert.notEqual(JSON.parse(pv.payload_json).feedHash,'old')})});
test('SMN_CURRENT_HASH_FULL_SCAN_REQUIRED_FOR_CAN_SAY_NO_ACTIVE',async()=>{const d=db();await mock(rss(21),async()=>{const first=await smnFeed({HAZARD_DB:d},new Date(NOW),d);assert.equal(first.verification.state,'DEGRADED_PARTIAL_FEED');assert.equal(first.verification.canSayNoActiveOfficialWarnings,false);await persistHazardRecords(d,first.allRecords);await persistProviderVerification(d,'smn-cap',first.verification,Date.parse(NOW));const second=await smnFeed({HAZARD_DB:d},new Date('2026-08-28T11:11:00Z'),d);assert.equal(second.verification.state,'FRESH_PARSED');assert.equal(second.verification.scanCompleted,true);assert.equal(second.verification.canSayNoActiveOfficialWarnings,true);assert.equal(second.verification.activeCount,21);assert.equal(second.verification.timestampAnomalies,21);assert.equal(second.verification.unreconciledTimestampAnomalies,0)})});
test('SMN_TRANSIENT_PARSE_FAILURE_FULL_RETRY_CAN_RECOVER',async()=>{const d=db(),feed=rss(2),old=globalThis.fetch;let fail=true;globalThis.fetch=async x=>{const u=String(x);if(u.includes('rss_alertaCAP'))return new Response(feed,{headers:{'content-type':'application/rss+xml'}});const m=u.match(/test_(\d+)\.xml/);if(m&&m[1]==='1'&&fail){fail=false;throw Error('transient')}if(m)return new Response(cap(`id-${m[1]}`),{headers:{'content-type':'application/xml'}});throw Error('bad fetch')};try{const a=await smnFeed({HAZARD_DB:d},new Date(NOW),d);assert.equal(a.verification.state,'DEGRADED_PARTIAL_FEED');assert.equal(a.verification.parseFailures,1);assert.equal(a.verification.canSayNoActiveOfficialWarnings,false);await persistHazardRecords(d,a.allRecords);await persistProviderVerification(d,'smn-cap',a.verification,Date.parse(NOW));const st=JSON.parse(d.raw.prepare("SELECT payload_json FROM runtime_state WHERE key='smn:scan'").get().payload_json);assert.equal(st.cursor,0);assert.equal(st.parseFailures,0);assert.equal(st.completed,false);assert.equal(st.lastFailedPassParseFailures,1);const b=await smnFeed({HAZARD_DB:d},new Date('2026-08-28T11:11:00Z'),d);assert.equal(b.verification.state,'FRESH_PARSED');assert.equal(b.verification.parseFailures,0);assert.equal(b.verification.activeCount,2);assert.equal(b.verification.canSayNoActiveOfficialWarnings,true)}finally{globalThis.fetch=old}});
