import type { Snapshot } from '../../../domain/snapshot';
import { SafeSparkline } from '../../components/ui/SafeSparkline';

function trend(value: string): string { return value === 'RISING' ? 'Subiendo' : value === 'RISING_SLOWLY' ? 'Subiendo lentamente' : value === 'FALLING' ? 'Bajando' : value === 'STABLE' ? 'Estable' : 'Sin tendencia'; }

export function LiveOverview({ snapshot }: { readonly snapshot: Snapshot }) {
  const systems = snapshot.systems ?? [];
  return <section className="v3-card now-overview" aria-labelledby="current-state-title" data-testid="current-state-panel" data-primary-section="true"><header className="v3-card__header"><div><span className="v3-eyebrow">Lecturas separadas</span><h2 id="current-state-title">Estado actual</h2></div><span className={`status-chip status-chip--${(snapshot.dataStatus ?? 'UNAVAILABLE').toLowerCase()}`}>{snapshot.dataStatus === 'LIVE' ? 'En vivo' : snapshot.dataStatus === 'STALE' ? 'Desactualizado' : snapshot.dataStatus === 'OFFLINE' ? 'Sin conexión' : 'Sin datos'}</span></header><div className="system-summary-list">{systems.map((system) => <article className="system-summary" data-testid={`current-system-${system.id}`} aria-label={`${system.watercourse}, estación ${system.stationName}`} key={system.id}><div><strong>{system.label}</strong><span>{system.watercourse} · {system.stationName}</span></div><div className="system-summary__value"><strong>{system.available && system.currentMetres !== null ? `${system.currentMetres.toFixed(2)} m` : '—'}</strong><span>{trend(system.trend)}</span></div><SafeSparkline values={system.points.map((point) => point.metres)} label={`${system.watercourse}, estación ${system.stationName}`} description={system.available ? `${system.points.length} lecturas publicadas; última lectura ${system.currentMetres?.toFixed(2)} metros.` : 'Sin lecturas publicadas disponibles.'}/></article>)}{systems.length === 0 && <p>Sin estaciones con lecturas publicadas disponibles.</p>}</div></section>;
}
