import{haversineKm,nullableNumber,codepointCompare}from'./hazard.js';
const ROLES=new Set(['OFFICIAL_LOCAL_OR_NATIONAL_OBSERVATION','SUPPLEMENTARY_EXTERNAL_OBSERVATION','SUPPLEMENTARY_SATELLITE_ESTIMATE','SUPPLEMENTARY_EXTERNAL_EVENT_SIGNAL','SUPPLEMENTARY_MODEL_FORECAST','OFFICIAL_IMPACT_REPORT']);
const roleRank=role=>({OFFICIAL_WARNING:0,OFFICIAL_IMPACT_REPORT:1,OFFICIAL_LOCAL_OR_NATIONAL_OBSERVATION:2,SUPPLEMENTARY_EXTERNAL_OBSERVATION:3,SUPPLEMENTARY_EXTERNAL_EVENT_SIGNAL:4,SUPPLEMENTARY_SATELLITE_ESTIMATE:5,SUPPLEMENTARY_MODEL_FORECAST:6}[role]??9);
const severityRank=s=>({Extreme:0,Severe:1,Moderate:2,Minor:3}[String(s||'')]??9);
function evidenceKindForRole(role){if(role==='OFFICIAL_WARNING')return'WARNING';if(String(role||'').startsWith('SUPPLEMENTARY_'))return'SUPPLEMENTARY';return'OBSERVATION'}
const finiteCoord=(v,min,max)=>{const n=Number(v);return Number.isFinite(n)&&n>=min&&n<=max?n:null};
export function canonicalObservation(input){if(!input||typeof input!=='object'||Array.isArray(input))throw new Error('OBSERVATION_INVALID');for(const k of['observationId','observationType','providerId','sourceOrganization','sourceRole','label'])if(typeof input[k]!=='string'||!input[k].trim())throw new Error(`OBSERVATION_${k.toUpperCase()}_INVALID`);if(!ROLES.has(input.sourceRole))throw new Error('OBSERVATION_SOURCE_ROLE_INVALID');let geometry=null,lon=null,lat=null;if(input.geometry?.type==='Point'&&Array.isArray(input.geometry.coordinates)){lon=finiteCoord(input.geometry.coordinates[0],-180,180);lat=finiteCoord(input.geometry.coordinates[1],-90,90);if(lon!==null&&lat!==null)geometry=Object.freeze({type:'Point',coordinates:Object.freeze([lon,lat])})}const value=nullableNumber(input.value),delta24h=nullableNumber(input.delta24h);return Object.freeze({...input,geometry,lon,lat,value,delta24h,isWarning:false,isCurrent:input.freshness==='FRESH',metadata:Object.freeze({...input.metadata})})}
export function observationDistanceKm(reference,observation){const lon=finiteCoord(reference?.lon,-180,180),lat=finiteCoord(reference?.lat,-90,90);if(lon===null||lat===null||!observation?.geometry||observation.geometry.type!=='Point')return null;const[olon,olat]=observation.geometry.coordinates;return haversineKm([lon,lat],[olon,olat])}
function eventPoint(e){if(e?.geometry?.type==='Point'&&Array.isArray(e.geometry.coordinates))return e.geometry.coordinates;if(Array.isArray(e?.bbox)&&e.bbox.length===4)return[(e.bbox[0]+e.bbox[2])/2,(e.bbox[1]+e.bbox[3])/2];return null}
function warningDistance(reference,e){const p=eventPoint(e);if(!p)return null;return haversineKm([reference.lon,reference.lat],p)}
function affectsReference(reference,e){if(!Array.isArray(e?.bbox)||e.bbox.length!==4)return false;return reference.lon>=e.bbox[0]&&reference.lon<=e.bbox[2]&&reference.lat>=e.bbox[1]&&reference.lat<=e.bbox[3]}
export function rankNearbyEvidence(reference,events=[],observations=[]){const out=[];for(const e of events){const sourceRole=e.sourceRole||e.sources?.[0]?.sourceRole||e.records?.[0]?.sourceRole||'OFFICIAL_WARNING',distanceKm=warningDistance(reference,e);const evidenceKind=evidenceKindForRole(sourceRole);out.push({id:e.eventId,evidenceKind,sourceRole,hazardType:e.hazardType||null,severity:evidenceKind==='WARNING'?e.displaySeverity??null:null,freshness:e.freshness||'UNAVAILABLE',affectsReference:affectsReference(reference,e),distanceKm,item:e})}for(const o of observations){const distanceKm=observationDistanceKm(reference,o);out.push({id:o.observationId,evidenceKind:'OBSERVATION',sourceRole:o.sourceRole,hazardType:o.hazardType||null,severity:null,freshness:o.freshness||'UNAVAILABLE',affectsReference:false,distanceKm,item:o})}return out.sort((a,b)=>Number(b.affectsReference)-Number(a.affectsReference)||roleRank(a.sourceRole)-roleRank(b.sourceRole)||severityRank(a.severity)-severityRank(b.severity)||(a.distanceKm===null?1:b.distanceKm===null?-1:a.distanceKm-b.distanceKm)||Date.parse(b.item.observedAt||b.item.lastChangedAt||0)-Date.parse(a.item.observedAt||a.item.lastChangedAt||0)||codepointCompare(a.id,b.id))}
function normHeadline(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim().replace(/\s+/g,' ')}
function provider(e){return e.sources?.[0]?.providerId||e.records?.[0]?.providerId||e.providerId||null}
function overlap(a,b){const as=Date.parse(a.firstSeenAt||a.lastChangedAt||''),bs=Date.parse(b.firstSeenAt||b.lastChangedAt||''),ae=Date.parse(a.expiresAt||a.lastChangedAt||''),be=Date.parse(b.expiresAt||b.lastChangedAt||'');if(!Number.isFinite(as)||!Number.isFinite(bs))return false;const A=Number.isFinite(ae)?ae:as+72*3600000,B=Number.isFinite(be)?be:bs+72*3600000;return as<=B&&bs<=A}
export function clusterPresentationEvents(events=[]){const clusters=[];for(const e of events){const sourceRole=e.sources?.[0]?.sourceRole||e.records?.[0]?.sourceRole||e.sourceRole||null,key=sourceRole!=='OFFICIAL_WARNING'?`event|${e.eventId}`:[e.hazardType||'',provider(e)||'',normHeadline(e.dominantHeadline),e.displaySeverity||''].join('|');let c=clusters.find(x=>x.key===key&&overlap(x.events[0],e));if(!c){c={key,events:[]};clusters.push(c)}c.events.push(e)}return clusters.map(c=>Object.freeze({eventIds:Object.freeze(c.events.map(e=>e.eventId).sort(codepointCompare)),hazardType:c.events[0].hazardType,providerId:provider(c.events[0]),displaySeverity:c.events[0].displaySeverity??null,headline:c.events[0].dominantHeadline||'',events:Object.freeze([...c.events])}))}
