import { expect, test, type Page } from '@playwright/test';
import type { HydrologicalSystem, Snapshot, Source } from '../../src/domain/snapshot.ts';
import { stableHydrometricSnapshot } from './fixtures/stable-hydrometric.ts';

const generatedAt=stableHydrometricSnapshot.generatedAt;
const validUntil=new Date(Date.parse(generatedAt)+24*60*60_000).toISOString();
function sourceFor(system: HydrologicalSystem): Source { return { id:system.sourceId,name:`INA REST · ${system.watercourse}`,kind:'OFFICIAL_OBSERVATION',status:'FRESH',observedAt:generatedAt,fetchedAt:generatedAt,lastCheckedAt:generatedAt,validUntil,contribution:'fixture 028',official:true,connected:true,organizationId:'ina',organizationName:'Instituto Nacional del Agua',feedId:system.sourceId,feedName:system.sourceName,classification:'OPERATIONAL_FRESH',freshness:'ACTUALIZADO',determinesPrimaryState:true,url:'https://alerta.ina.gob.ar/' }; }
function salado(current=3.42): HydrologicalSystem { const points=Array.from({length:190},(_,i)=>({at:new Date(Date.parse(generatedAt)-(189-i)*3600000).toISOString(),metres:current-(189-i)*.001,measured:true,quality:'PUBLISHED_OPERATIONAL' as const})); return {id:'salado-santo-tome',label:'Río Salado — Santo Tomé',watercourse:'Río Salado',stationName:'Santo Tomé',stationCode:'3044',available:true,dataStatus:'LIVE',freshness:'ACTUALIZADO',currentMetres:current,observedAt:generatedAt,fetchedAt:generatedAt,validUntil,sourceId:'ina-rest-3044',sourceName:'Instituto Nacional del Agua · INA REST',points,thresholds:[{id:'ALERTA',label:'Nivel de alerta de referencia',metres:4.7}],trend:'RISING_SLOWLY',delta1h:.001,delta6h:.006,delta24h:.024,delta72h:.072,delta7d:.168}; }
function parana(): HydrologicalSystem { const base=stableHydrometricSnapshot.systems![0]!; const points=Array.from({length:190},(_,i)=>({at:new Date(Date.parse(generatedAt)-(189-i)*3600000).toISOString(),metres:3.2-(189-i)*.002,measured:true,quality:'PUBLISHED_OPERATIONAL' as const})); return {...base,points,validUntil,delta72h:.144,delta7d:.336}; }
function data(id='028-e2e',saladoLevel=3.42): Snapshot { const p=parana(),s=salado(saladoLevel); return {...stableHydrometricSnapshot,id,generatedAt,validUntil,systems:[p,s],sources:[sourceFor(p),sourceFor(s)],river:{...stableHydrometricSnapshot.river,systemId:p.id,stationName:p.stationName,currentMetres:p.currentMetres,delta1h:p.delta1h,delta6h:p.delta6h,delta24h:p.delta24h,trend:p.trend,observedAt:p.observedAt!,fetchedAt:p.fetchedAt!,validUntil,sourceId:p.sourceId,points:p.points,thresholds:p.thresholds}}; }
async function baseRoutes(page: Page, snapshots: Snapshot[]) { let index=0; await page.route('**/api/snapshot*',route=>{ const snapshot=snapshots[Math.min(index++,snapshots.length-1)]!; return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({ok:true,data:snapshot})});}); await page.route('**/api/auth/config*',route=>route.fulfill({json:{ok:true,data:{enabled:false,reportingEnabled:true,googleClientId:null}}})); await page.route('**/api/session*',route=>route.fulfill({json:{ok:true,data:{enabled:false,authenticated:false,principal:null}}})); }

test('028 keeps hydrometry primary and does not load external map sources until explicit open',async({page},testInfo)=>{ test.skip(testInfo.project.name!=='desktop'); await page.setViewportSize({width:390,height:844}); const external:string[]=[]; page.on('request',request=>{ if(/wms\.ign\.gob\.ar|aswe\.santafe\.gov\.ar/.test(request.url())) external.push(request.url()); }); await baseRoutes(page,[data()]); await page.goto('/'); await expect(page.getByRole('heading',{level:1,name:'Situación hidrométrica'})).toBeVisible(); await expect(page.getByTestId('flood-situation')).toHaveAttribute('data-flood-state','ROUTINE'); await expect(page.getByTestId('main-hydro-chart')).toHaveAttribute('data-window-sufficient','true'); expect(external).toHaveLength(0); await expect(page.getByTestId('situation-map')).toHaveCount(0); await page.route('https://wms.ign.gob.ar/**',route=>route.fulfill({status:204})); await page.route('https://aswe.santafe.gov.ar/**',route=>route.fulfill({status:500})); await page.getByTestId('open-situation-map').click(); await expect(page.getByTestId('situation-map')).toBeVisible(); await expect(page.getByTestId('situation-map')).toContainText('No representa una zona inundada ahora'); await expect.poll(()=>external.length).toBeGreaterThan(0); await expect(page.getByTestId('hydro-current-level')).toBeVisible(); });

test('028 selected Salado persists across a fresh snapshot refresh',async({page},testInfo)=>{ test.skip(testInfo.project.name!=='desktop'); const first=data('028-before',3.42),second=data('028-after',3.43); await baseRoutes(page,[first,second]); await page.goto('/'); await expect(page.locator('main')).toHaveAttribute('data-snapshot-id','028-before'); await page.getByRole('tab',{name:'Salado'}).click(); await expect(page.getByTestId('hydro-current-level')).toContainText('3,42'); await page.getByRole('button',{name:'Actualizar información'}).first().click(); await expect(page.locator('main')).toHaveAttribute('data-snapshot-id','028-after'); await expect(page.getByRole('tab',{name:'Salado'})).toHaveAttribute('aria-selected','true'); await expect(page.getByTestId('hydro-current-level')).toContainText('3,43'); });

test('028 sparse 24h data never falls back to older points',async({page},testInfo)=>{ test.skip(testInfo.project.name!=='desktop'); const snapshot=data('028-gap'); const p=snapshot.systems![0]!; const latest=p.points.at(-1)!; const old={...p.points[0]!,at:new Date(Date.parse(latest.at)-30*3600000).toISOString()}; const sparse={...p,points:[old,latest],delta1h:null,delta6h:null,delta24h:null,trend:'UNKNOWN' as const}; const gap:Snapshot={...snapshot,systems:[sparse,snapshot.systems![1]!],river:{...snapshot.river,points:sparse.points,delta1h:null,delta6h:null,delta24h:null,trend:'UNKNOWN'}}; await baseRoutes(page,[gap]); await page.goto('/'); const chart=page.getByTestId('main-hydro-chart'); await expect(chart).toHaveAttribute('data-window-sufficient','false'); await expect(chart).toContainText('No hay cobertura suficiente en 24 h'); await expect(chart).toContainText('No se completan huecos'); });
