import{bboxOfPolygon,publicRecord,freshness,canonicalRecordCompare}from'../domain/hazard.js';
const MAX_XML_BYTES=1500000,MAX_VERTICES=2000;
const de=s=>String(s||'').replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/&#x([0-9A-F]+);/gi,(_,h)=>String.fromCodePoint(parseInt(h,16))).replace(/&#(\d+);/g,(_,d)=>String.fromCodePoint(Number(d))).replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&apos;/g,"'");
const tag=(x,n)=>de((x.match(new RegExp(`<${n}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${n}>`,'i'))||[])[1]?.trim()||'');
const tags=(x,n)=>[...x.matchAll(new RegExp(`<${n}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${n}>`,'gi'))].map(m=>de(m[1].trim()));
export function rejectUnsafeXml(xml){if(typeof xml!=='string'||new TextEncoder().encode(xml).byteLength>MAX_XML_BYTES)throw new Error('CAP_SIZE');if(/<!DOCTYPE|<!ENTITY|SYSTEM\s+['"]|PUBLIC\s+['"]/i.test(xml))throw new Error('CAP_XML_UNSAFE');if(!/^\s*(?:<\?xml[^>]*>\s*)?(?:<\?xml-stylesheet[^>]*>\s*)?<[^>]+/i.test(xml))throw new Error('CAP_MALFORMED');return xml}
export function parseRssLinks(xml){rejectUnsafeXml(xml);if(!/<rss\b|<feed\b/i.test(xml))throw new Error('SMN_RSS_PARSE');const out=[...xml.matchAll(/<item>([\s\S]*?)<\/item>/gi)].map(m=>({title:tag(m[1],'title'),link:tag(m[1],'link'),description:tag(m[1],'description'),pubDate:tag(m[1],'pubDate')})).filter(x=>/^https:\/\/ssl\.smn\.gob\.ar\/feeds\/CAP\/xml_generados\/[A-Za-z0-9_.~-]+\.xml$/.test(x.link));if(out.length>200)throw new Error('SMN_RSS_ITEM_CAP');return out}
function polygonFrom(raw){if(!raw)return[];const tokens=raw.trim().split(/\s+/);if(tokens.length>MAX_VERTICES)throw new Error('CAP_POLYGON_VERTEX_CAP');const out=[];for(const token of tokens){const parts=token.split(',');if(parts.length!==2)throw new Error('CAP_POLYGON_INVALID');const lat=Number(parts[0]),lon=Number(parts[1]);if(!Number.isFinite(lat)||!Number.isFinite(lon)||lat< -90||lat>90||lon< -180||lon>180)throw new Error('CAP_POLYGON_INVALID');out.push([lon,lat])}return out}
export function parseCapReference(value){const parts=String(value||'').split(',');if(parts.length<3)return null;const sender=parts[0]?.trim(),identifier=parts[1]?.trim(),sent=parts.slice(2).join(',').trim();if(!sender||!identifier||!Number.isFinite(Date.parse(sent)))return null;return{sender,identifier,sent:new Date(sent).toISOString()}}
export function parseCapReferences(value){return String(value||'').trim().split(/\s+/).map(parseCapReference).filter(Boolean)}
export const SMN_CAP_SENT_OFFSET_ANOMALY='SMN_CAP_SENT_OFFSET_ANOMALY';
const SMN_SENT_OFFSET_RE=/^(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2})(?:\.\d+)?-03:00$/;
const isoOrNull=v=>v&&Number.isFinite(Date.parse(v))?new Date(v).toISOString():null;
function smnWallClockUtc(sentRaw){const m=String(sentRaw||'').match(SMN_SENT_OFFSET_RE);return m?isoOrNull(`${m[1]}Z`):null}
export function reconcileSmnTimestamp(sentRaw,rssPubDateRaw,fetchedAt=new Date().toISOString()){
  const capSentParsedAt=isoOrNull(sentRaw),rssPubDate=isoOrNull(rssPubDateRaw),fetchMs=Date.parse(fetchedAt);
  if(!capSentParsedAt||!Number.isFinite(fetchMs))return{capSentRaw:String(sentRaw||''),capSentParsedAt,rssPubDateRaw:rssPubDateRaw||null,rssPubDate,timestampBasis:'CAP_SENT_INVALID',timestampAnomaly:'UNRECONCILED_CAP_SENT',effectivePublicationAt:null,reconciled:false};
  const capState=freshness(capSentParsedAt,fetchMs,12*3600000,72*3600000);
  if(capState!=='FUTURE_REJECTED')return{capSentRaw:sentRaw,capSentParsedAt,rssPubDateRaw:rssPubDateRaw||null,rssPubDate,timestampBasis:'CAP_SENT',timestampAnomaly:null,effectivePublicationAt:capSentParsedAt,reconciled:false};
  const wallClockUtc=smnWallClockUtc(sentRaw),rssState=rssPubDate?freshness(rssPubDate,fetchMs,12*3600000,72*3600000):'UNAVAILABLE',wallState=wallClockUtc?freshness(wallClockUtc,fetchMs,12*3600000,72*3600000):'UNAVAILABLE';
  const offsetMs=wallClockUtc?Date.parse(capSentParsedAt)-Date.parse(wallClockUtc):NaN,sameItemWindowMs=wallClockUtc&&rssPubDate?Math.abs(Date.parse(wallClockUtc)-Date.parse(rssPubDate)):Infinity;
  const demonstratedPattern=wallClockUtc&&rssPubDate&&rssState==='FRESH'&&wallState==='FRESH'&&Math.abs(offsetMs-3*3600000)<=1000&&sameItemWindowMs<=30*60000;
  if(demonstratedPattern)return{capSentRaw:sentRaw,capSentParsedAt,rssPubDateRaw:rssPubDateRaw||null,rssPubDate,timestampBasis:'RSS_PUBDATE_RECONCILED',timestampAnomaly:SMN_CAP_SENT_OFFSET_ANOMALY,effectivePublicationAt:rssPubDate,reconciled:true};
  return{capSentRaw:sentRaw,capSentParsedAt,rssPubDateRaw:rssPubDateRaw||null,rssPubDate,timestampBasis:'CAP_SENT_UNRECONCILED',timestampAnomaly:'UNRECONCILED_FUTURE_CAP_SENT',effectivePublicationAt:null,reconciled:false};
}
export function parseCap(xml,{sourceUrl='',fetchedAt=new Date().toISOString(),rawHash=null,rssPubDate=null}={}){rejectUnsafeXml(xml);if(!/<alert\b/i.test(xml))throw new Error('CAP_MALFORMED');const status=tag(xml,'status'),msgType=tag(xml,'msgType'),scope=tag(xml,'scope'),identifier=tag(xml,'identifier'),sender=tag(xml,'sender'),sent=tag(xml,'sent');if(!identifier||!sender||!sent||!status||!msgType||!scope||!Number.isFinite(Date.parse(sent)))throw new Error('CAP_REQUIRED');if(!['Actual','Exercise','System','Test','Draft'].includes(status))throw new Error('CAP_STATUS_INVALID');if(!['Alert','Update','Cancel','Ack','Error'].includes(msgType))throw new Error('CAP_MSGTYPE_INVALID');const polygon=polygonFrom(tag(xml,'polygon'));const expiresRaw=tag(xml,'expires'),expires=expiresRaw&&Number.isFinite(Date.parse(expiresRaw))?new Date(expiresRaw).toISOString():null;const fetchMs=Date.parse(fetchedAt),timestamp=reconcileSmnTimestamp(sent,rssPubDate,fetchedAt),basisAt=timestamp.effectivePublicationAt||timestamp.capSentParsedAt,sentFreshness=freshness(basisAt,fetchMs,12*3600000,72*3600000);const publicMessage=status==='Actual'&&['Alert','Update','Cancel'].includes(msgType)&&scope==='Public';const expired=expires!==null&&Date.parse(expires)<=fetchMs;let lifecycle='SUPPRESSED';if(publicMessage){if(msgType==='Cancel')lifecycle='CANCELLED';else if(expired)lifecycle='EXPIRED';else lifecycle='ACTIVE'}const references=parseCapReferences(tag(xml,'references'));const unreconciled=timestamp.timestampBasis==='CAP_SENT_UNRECONCILED';const recordFreshness=publicMessage&&!expired&&!unreconciled&&sentFreshness!=='FUTURE_REJECTED'?'FRESH':unreconciled?'FUTURE_REJECTED':sentFreshness;const verificationState=!publicMessage?'SUPPRESSED_NONPUBLIC':unreconciled?'DEGRADED_TIMESTAMP_ANOMALY':timestamp.reconciled?'VERIFIED_MACHINE_TIMESTAMP_RECONCILED':'VERIFIED_MACHINE';
return publicRecord({recordId:`smn-cap:${identifier}`,providerId:'smn-cap',providerRecordId:identifier,hazardType:(tag(xml,'event')||'METEOROLOGICAL').toUpperCase(),sourceRole:'OFFICIAL_WARNING',sourceOrganization:'Servicio Meteorológico Nacional',official:true,issuedAt:timestamp.capSentParsedAt,observedAt:null,effectiveAt:validDate(tag(xml,'effective')),onsetAt:validDate(tag(xml,'onset')),expiresAt:expires,fetchedAt:new Date(fetchMs).toISOString(),freshness:recordFreshness,verificationState,geometry:polygon.length?{type:'Polygon',coordinates:[polygon]}:null,bbox:bboxOfPolygon(polygon),regionCodes:[],headline:tag(xml,'headline')||tag(xml,'event')||'Alerta SMN',description:tag(xml,'description'),instruction:tag(xml,'instruction')||null,sourceUrl,attribution:'Servicio Meteorológico Nacional (SMN)',rawHash,schemaVersion:'1.0',capIdentifier:identifier,capLineageRoot:identifier,capSender:sender,capStatus:status,capMsgType:msgType,capScope:scope,capReferences:references,capCategory:tags(xml,'category'),capEvent:tag(xml,'event'),capResponseType:tags(xml,'responseType'),capUrgency:tag(xml,'urgency'),capSeverity:tag(xml,'severity'),capCertainty:tag(xml,'certainty'),capAreaDescriptions:tags(xml,'areaDesc'),capGeocodes:[],capSentRaw:timestamp.capSentRaw,capSentParsedAt:timestamp.capSentParsedAt,rssPubDateRaw:timestamp.rssPubDateRaw,rssPubDate:timestamp.rssPubDate,timestampBasis:timestamp.timestampBasis,timestampAnomaly:timestamp.timestampAnomaly,effectivePublicationAt:timestamp.effectivePublicationAt,lifecycle,publicMessage,currentImpact:false})}
function validDate(v){if(!v)return null;return Number.isFinite(Date.parse(v))?new Date(v).toISOString():null}
export function applyCapLifecycle(records){const normalized=[...records].sort(canonicalRecordCompare),byId=new Map();for(const r of normalized)byId.set(r.capIdentifier,Object.freeze({...r,capLineageRoot:r.capLineageRoot||r.capIdentifier}));const memo=new Map();function rootFor(id,stack=new Set()){if(memo.has(id))return memo.get(id);const r=byId.get(id);if(!r)return id;if(stack.has(id))return r.capIdentifier;const next=new Set(stack);next.add(id);let root=r.capIdentifier;if(['Update','Cancel'].includes(r.capMsgType)){const ref=(r.capReferences||[]).find(x=>byId.has(x.identifier));if(ref)root=rootFor(ref.identifier,next)}memo.set(id,root);return root}const out=new Map();for(const r of normalized)out.set(r.capIdentifier,Object.freeze({...r,capLineageRoot:rootFor(r.capIdentifier)}));for(const original of normalized){const r=out.get(original.capIdentifier);if(!['Update','Cancel'].includes(r.capMsgType))continue;for(const rr of r.capReferences||[]){const prev=out.get(rr.identifier);if(!prev)continue;out.set(rr.identifier,Object.freeze({...prev,lifecycle:r.capMsgType==='Cancel'?'CANCELLED':'SUPERSEDED',supersededBy:r.capIdentifier,capLineageRoot:rootFor(prev.capIdentifier)}))}}return[...out.values()].sort(canonicalRecordCompare)}
export function capPublicActive(r,now=Date.now()){return r.publicMessage===true&&r.lifecycle==='ACTIVE'&&r.freshness!=='FUTURE_REJECTED'&&r.verificationState!=='DEGRADED_TIMESTAMP_ANOMALY'&&(!r.expiresAt||Date.parse(r.expiresAt)>now)}
