export const SOURCE_REGISTRY_VERSION='2026-08-28.order031.v2';
const machineStatuses=new Set(['LIVE_MACHINE','STATIC_LAYER']);
const blockedStatuses=new Set(['BLOCKED_EXTERNAL_CREDENTIAL','BLOCKED_EXTERNAL_APPROVAL_OR_CREDENTIAL']);
const capability=(providerId,organization,sourceRole,hazards,coverage,transport,status,limitations,publicHumanUrl,machineEndpointAllowlist=[],extra={})=>Object.freeze({providerId,organization,sourceRole,hazards:Object.freeze(hazards),coverage,transport,machineReadable:machineStatuses.has(status),freshnessContract:status==='STATIC_LAYER'?'Static/historical context only; never current impact.':'Provider timestamps and fetch state must be validated before current claims.',licenseOrTerms:'Official/public-source terms; attribution retained.',attribution:organization,cost:0,requiresCredential:blockedStatuses.has(status),credentialState:blockedStatuses.has(status)?'NOT_CONFIGURED':'NONE',status,limitations:Object.freeze(limitations),publicHumanUrl,machineEndpointAllowlist:Object.freeze(machineEndpointAllowlist),...extra});
export const IGN_RISK_LAYERS=Object.freeze([
Object.freeze({id:'desinventar_hidrometeorologico_riesgo',title:'Amenazas hidrometeorológicas, registros DESINVENTAR',hazards:['FLOOD','STORM'],temporalSemantics:'HISTORICAL_STATIC_CONTEXT',wms:true}),
Object.freeze({id:'puertos_alturas_rios',title:'Registros de Puertos de la Cuenca del Plata, días de alerta y evacuación (2024)',hazards:['FLOOD'],temporalSemantics:'HISTORICAL_STATIC_CONTEXT',wms:true}),
Object.freeze({id:'mayds_sup_afectada_2022',title:'Superficie afectada por incendios, año 2022 MAyDS',hazards:['WILDFIRE'],temporalSemantics:'HISTORICAL_STATIC_CONTEXT',wms:true}),
Object.freeze({id:'inpres_sismos_zonificacion',title:'Sismos INPRES zonificación',hazards:['EARTHQUAKE'],temporalSemantics:'STATIC_RISK_CONTEXT',wms:true}),
Object.freeze({id:'segemar_riesgo_volcanico_2025',title:'Volcanes SEGEMAR riesgo relativo. 2025',hazards:['VOLCANO'],temporalSemantics:'STATIC_RISK_CONTEXT',wms:true})]);
export const SOURCE_REGISTRY=Object.freeze([
capability('smn-cap','Servicio Meteorológico Nacional','OFFICIAL_WARNING',['STORM','RAIN','WIND','SNOW','HEAT','COLD','METEOROLOGICAL'],'ARGENTINA','CAP_1_2_OVER_RSS','LIVE_MACHINE',[],'https://www.smn.gob.ar/alertas',['https://ssl.smn.gob.ar/feeds/CAP/']),
capability('ina','Instituto Nacional del Agua','OFFICIAL_LOCAL_OR_NATIONAL_OBSERVATION',['FLOOD'],'DOCUMENTED_STATIONS_ONLY','REST_WATERML','LIVE_MACHINE',['National coverage is not inferred beyond verified station contracts.'],'https://www.argentina.gob.ar/ina',['https://alerta.ina.gob.ar/a5/']),
capability('inpres','Instituto Nacional de Prevención Sísmica','OFFICIAL_LOCAL_OR_NATIONAL_OBSERVATION',['EARTHQUAKE'],'ARGENTINA','PUBLIC_HTML_STRICT','LIVE_MACHINE',['Public HTML table, not a documented API. Markup/schema drift fails closed.'],'https://www.inpres.gob.ar/sismos_consultados',['https://www.inpres.gob.ar/sismos_consultados']),
capability('usgs-earthquake','USGS Earthquake Hazards Program','SUPPLEMENTARY_EXTERNAL_OBSERVATION',['EARTHQUAKE'],'ARGENTINA_BOUNDED_QUERY','FDSN_GEOJSON','LIVE_MACHINE',['External-government observation is supplementary corroboration/fallback and never an Argentine official warning.'],'https://earthquake.usgs.gov/earthquakes/',['https://earthquake.usgs.gov/fdsnws/event/1/query']),
capability('nasa-eonet','NASA EONET','SUPPLEMENTARY_EXTERNAL_EVENT_SIGNAL',['WILDFIRE'],'ARGENTINA_BOUNDED_QUERY','JSON_REST_V3','LIVE_MACHINE',['Open-event signal only; never confirms an official Argentine fire emergency.'],'https://eonet.gsfc.nasa.gov/',['https://eonet.gsfc.nasa.gov/api/v3/events']),
capability('georef','API GeoRef','OFFICIAL_GEOREFERENCE',[],'ARGENTINA','JSON_REST','LIVE_MACHINE',['Georeference only; never hazard evidence.'],'https://www.argentina.gob.ar/georef',['https://apis.datos.gob.ar/georef/api/']),
capability('argenmap','Instituto Geográfico Nacional','OFFICIAL_BASEMAP',[],'ARGENTINA','WMS','LIVE_MACHINE',['Basemap only; never hazard evidence.'],'https://www.ign.gob.ar/NuestrasActividades/InformacionGeoespacial/ServiciosOGC',['https://wms.ign.gob.ar/geoserver/wms']),
capability('ign-risk','Instituto Geográfico Nacional / IG-GIRD','OFFICIAL_STATIC_RISK_CONTEXT',['FLOOD','WILDFIRE','EARTHQUAKE','VOLCANO'],'ARGENTINA_WHERE_LAYERS_EXIST','WMS','STATIC_LAYER',['Static susceptibility, historical records and risk context never mean affected now.'],'https://riesgo.ign.gob.ar/',['https://wms.ign.gob.ar/geoserver/ign_riesgo/ows'],{layers:IGN_RISK_LAYERS}),
capability('nasa-gpm','NASA GPM IMERG','SUPPLEMENTARY_SATELLITE_ESTIMATE',['RAIN'],'SANTA_FE_POINT_SPECIALIST','ARCGIS_IMAGESERVER','LIVE_MACHINE',['Current machine adapter is intentionally scoped to one Santa Fe point; satellite estimate never becomes an official warning.'],'https://gpm.nasa.gov/data/imerg',['https://gis.earthdata.nasa.gov/image/rest/services/GESDISC/GPM_3IMERGHHE/ImageServer']),
capability('fire','Servicio Nacional de Manejo del Fuego','OFFICIAL_STATIC_RISK_CONTEXT',['WILDFIRE'],'ARGENTINA','HUMAN_REFERENCE','HUMAN_LINK_ONLY',['Official institutional/reference source; no stable public machine contract proven for this release.'],'https://www.argentina.gob.ar/ambiente/fuego'),
capability('siname','SINAME / SINAGIR','OFFICIAL_IMPACT_REPORT',['MULTI_HAZARD'],'ARGENTINA','HUMAN_REFERENCE','HUMAN_LINK_ONLY',['Institutional reference only; no public machine contract or dispatch integration is claimed.'],'https://www.argentina.gob.ar/sinagir'),
capability('google-flood','Google Flood Forecasting','SUPPLEMENTARY_MODEL_FORECAST',['FLOOD'],'PROVIDER_DEFINED','REST','BLOCKED_EXTERNAL_APPROVAL_OR_CREDENTIAL',['No-charge API requires waitlist approval, project/API enablement and credential; not used for safety claims until authorized.'],'https://developers.google.com/flood-forecasting')]);
export const registryPublic=()=>({version:SOURCE_REGISTRY_VERSION,capabilities:SOURCE_REGISTRY.map(x=>({...x,machineEndpointAllowlist:x.machineEndpointAllowlist.map(u=>new URL(u).origin)}))});
