import{SOURCE_REGISTRY,IGN_RISK_LAYERS,registryPublic,SOURCE_REGISTRY_VERSION}from'../providers/registry.js';
import{parseCap,parseRssLinks,applyCapLifecycle,capPublicActive}from'../providers/cap.js';
import{parseInpresHtml}from'../providers/inpres.js';
import{parseUsgsGeoJson}from'../providers/usgs.js';
import{parseEonetWildfires}from'../providers/eonet.js';
import{parseBbox,bboxIntersects,publicRecord,reconcile,freshness}from'../domain/hazard.js';
import{safeFetch}from'./transport.js';
import{loadInaSeriesMetadata,riverObservationsFromSnapshot}from'../providers/ina-observations.js';
const SMN={hosts:['ssl.smn.gob.ar'],paths:[/^\/feeds\/CAP\//],maxBytes:1600000,timeoutMs:7000,contentTypes:['xml','text/plain'],accept:'application/xml,text/xml,application/rss+xml,text/plain'};
const GEO={hosts:['apis.datos.gob.ar'],paths:[/^\/georef\/api\/localidades$/],maxBytes:500000,timeoutMs:6000,contentTypes:['json'],accept:'application/json'};
const INPRES={hosts:['www.inpres.gob.ar'],paths:[/^\/sismos_consultados$/],maxBytes:900000,timeoutMs:8000,contentTypes:['html'],accept:'text/html'};
const USGS={hosts:['earthquake.usgs.gov'],paths:[/^\/fdsnws\/event\/1\/query$/],maxBytes:1000000,timeoutMs:8000,contentTypes:['json'],accept:'application/geo+json,application/json'};
const EONET={hosts:['eonet.gsfc.nasa.gov'],paths:[/^\/api\/v3\/events$/],maxBytes:1000000,timeoutMs:8000,contentTypes:['json','rss+xml'],accept:'application/json'};
const SMN_CHUNK=20;
const NASA_POINT={lon:-60.7,lat:-31.63,bbox:[-60.75,-31.68,-60.65,-31.58],regionCodes:['AR-S']};
export const j=(data,status=200,cache='no-store')=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':cache}});
export const safeErr=(code,status=400,detail=null)=>j({ok:false,error:{code,...(detail?{detail}: {})}},status);
function sourceUrl(snapshot,id,fallback){return(snapshot.sources||[]).find(x=>x.id===id)?.url||fallback}
async function runtimeState(db,key){if(!db)return null;const row=await db.prepare('SELECT payload_json,updated_at FROM runtime_state WHERE key=? LIMIT 1').bind(key).first();if(!row)return null;try{return{...JSON.parse(row.payload_json),updatedAt:row.updated_at}}catch{return null}}
async function setRuntimeState(db,key,payload,now){if(!db)return;await db.prepare("INSERT INTO runtime_state(key,payload_json,updated_at) VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET payload_json=excluded.payload_json,updated_at=excluded.updated_at").bind(key,JSON.stringify(payload),new Date(now).toISOString()).run()}
async function replaceSmnVerification(db,v,stamp){if(!db)return;const payload=JSON.stringify({...v,providerId:'smn-cap'});await db.prepare("INSERT INTO provider_verification(provider_id,state,verified_at,active_count,can_say_no_active,parse_failures,feed_item_count,error_class,payload_json,updated_at) VALUES('smn-cap',?,?,?,?,?,?,?,?,?) ON CONFLICT(provider_id) DO UPDATE SET state=excluded.state,verified_at=excluded.verified_at,active_count=excluded.active_count,can_say_no_active=excluded.can_say_no_active,parse_failures=excluded.parse_failures,feed_item_count=excluded.feed_item_count,error_class=excluded.error_class,payload_json=excluded.payload_json,updated_at=excluded.updated_at").bind(v.state,stamp,v.activeCount??null,v.canSayNoActiveOfficialWarnings===true?1:0,v.parseFailures??null,v.feedItemCount??null,v.errorClass||null,payload,stamp).run()}
function degradedScanVerification({stamp,feedHash,links,scan,state='DEGRADED_PARTIAL_FEED',errorClass='PARTIAL_FEED_SCAN'}){return{state,fetchedAt:stamp,activeCount:null,canSayNoActiveOfficialWarnings:false,parseFailures:scan.parseFailures||0,feedItemCount:links.length,errorClass,feedHash,scanCompleted:false,timestampAnomalies:scan.timestampAnomalies||0,unreconciledTimestampAnomalies:scan.unreconciledTimestampAnomalies||0}}
export async function smnFeed(env={},now=new Date(),db=env.HAZARD_DB||null){
 if(env.SOS_TEST_CAP_XML){const r=parseCap(env.SOS_TEST_CAP_XML,{sourceUrl:'fixture://smn',fetchedAt:now.toISOString(),rawHash:'fixture',rssPubDate:env.SOS_TEST_RSS_PUBDATE||null}),active=capPublicActive(r,now.getTime())?[r]:[],bad=r.verificationState==='DEGRADED_TIMESTAMP_ANOMALY';return{records:active,allRecords:[r],verification:{state:bad?'DEGRADED_TIMESTAMP_ANOMALY':'FIXTURE_PARSED',fetchedAt:now.toISOString(),activeCount:bad?null:active.length,canSayNoActiveOfficialWarnings:!bad,parseFailures:0,feedItemCount:1,timestampAnomalies:r.timestampAnomaly?1:0,unreconciledTimestampAnomalies:bad?1:0}}}
 const rss=`https://ssl.smn.gob.ar/feeds/CAP/rss_alertaCAP_nuevo_${now.getUTCFullYear()}.xml`;
 try{
  const feed=await safeFetch(rss,SMN),links=parseRssLinks(feed.body),feedHash=feed.rawHash||feed.etag||feed.lastModified||String(links.length),stamp=now.toISOString();
  let scan=await runtimeState(db,'smn:scan');const newHash=!scan||scan.feedHash!==feedHash;if(newHash){scan={feedHash,cursor:0,parseFailures:0,startedAt:stamp,completed:false,timestampAnomalies:0,unreconciledTimestampAnomalies:0};if(db)await replaceSmnVerification(db,degradedScanVerification({stamp,feedHash,links,scan}),stamp)}
  if(scan.completed&&db){const pv=await db.prepare("SELECT state,verified_at,active_count,can_say_no_active,parse_failures,feed_item_count,error_class,payload_json FROM provider_verification WHERE provider_id='smn-cap' LIMIT 1").first();let detail={};try{detail=JSON.parse(pv?.payload_json||'{}')}catch{}if(detail.feedHash!==feedHash||detail.scanCompleted!==true){const v=degradedScanVerification({stamp,feedHash,links,scan});await replaceSmnVerification(db,v,stamp);return{records:[],allRecords:[],verification:v}}return{records:[],allRecords:[],verification:{state:pv?.state||'DEGRADED_PARTIAL_FEED',fetchedAt:pv?.verified_at||stamp,activeCount:pv?.can_say_no_active===1?pv?.active_count??0:null,canSayNoActiveOfficialWarnings:pv?.can_say_no_active===1,parseFailures:pv?.parse_failures??0,feedItemCount:pv?.feed_item_count??links.length,errorClass:pv?.error_class||null,feedEtag:feed.etag||null,feedLastModified:feed.lastModified||null,feedHash,scanCompleted:true,timestampAnomalies:detail.timestampAnomalies||0,unreconciledTimestampAnomalies:detail.unreconciledTimestampAnomalies||0}}}
  const end=Math.min(links.length,scan.cursor+SMN_CHUNK),parsed=[];let failures=0,chunkAnomalies=0,chunkUnreconciled=0;
  for(const item of links.slice(scan.cursor,end))try{const cap=await safeFetch(item.link,SMN),r=parseCap(cap.body,{sourceUrl:item.link,fetchedAt:stamp,rawHash:cap.rawHash,rssPubDate:item.pubDate});parsed.push(r);if(r.timestampAnomaly)chunkAnomalies++;if(r.verificationState==='DEGRADED_TIMESTAMP_ANOMALY')chunkUnreconciled++}catch{failures++}
  scan.cursor=end;scan.parseFailures=(scan.parseFailures||0)+failures;scan.timestampAnomalies=(scan.timestampAnomalies||0)+chunkAnomalies;scan.unreconciledTimestampAnomalies=(scan.unreconciledTimestampAnomalies||0)+chunkUnreconciled;const reachedEnd=end>=links.length;
  let failedPass=null;
  if(db&&reachedEnd){const rows=(await db.prepare("SELECT payload_json FROM hazard_records WHERE provider_id='smn-cap' AND fetched_at>=? ORDER BY fetched_at DESC LIMIT 250").bind(scan.startedAt).all()).results||[],prior=[];for(const row of rows)try{prior.push(JSON.parse(row.payload_json))}catch{}const lifecycle=applyCapLifecycle([...prior,...parsed]);if(scan.parseFailures===0){scan.completed=true;await setRuntimeState(db,'smn:scan',scan,now);if(scan.unreconciledTimestampAnomalies>0)return{records:parsed,allRecords:parsed,verification:{state:'DEGRADED_TIMESTAMP_ANOMALY',fetchedAt:stamp,activeCount:null,canSayNoActiveOfficialWarnings:false,parseFailures:0,feedItemCount:links.length,errorClass:'SMN_TIMESTAMP_ANOMALY_UNRECONCILED',feedEtag:feed.etag||null,feedLastModified:feed.lastModified||null,feedHash,scanCompleted:true,timestampAnomalies:scan.timestampAnomalies,unreconciledTimestampAnomalies:scan.unreconciledTimestampAnomalies}};const active=lifecycle.filter(r=>capPublicActive(r,now.getTime()));return{records:parsed,allRecords:parsed,verification:{state:'FRESH_PARSED',fetchedAt:stamp,activeCount:active.length,canSayNoActiveOfficialWarnings:true,parseFailures:0,feedItemCount:links.length,feedEtag:feed.etag||null,feedLastModified:feed.lastModified||null,feedHash,scanCompleted:true,timestampAnomalies:scan.timestampAnomalies,unreconciledTimestampAnomalies:0}}}failedPass={parseFailures:scan.parseFailures,timestampAnomalies:scan.timestampAnomalies||0,unreconciledTimestampAnomalies:scan.unreconciledTimestampAnomalies||0};scan={...scan,cursor:0,parseFailures:0,startedAt:stamp,completed:false,timestampAnomalies:0,unreconciledTimestampAnomalies:0,lastFailedPassAt:stamp,lastFailedPassParseFailures:failedPass.parseFailures};await setRuntimeState(db,'smn:scan',scan,now)}
  if(db)await setRuntimeState(db,'smn:scan',scan,now);
  const reportScan=failedPass?{...scan,...failedPass}:scan,state=reportScan.unreconciledTimestampAnomalies>0?'DEGRADED_TIMESTAMP_ANOMALY':'DEGRADED_PARTIAL_FEED',errorClass=reportScan.unreconciledTimestampAnomalies>0?'SMN_TIMESTAMP_ANOMALY_UNRECONCILED':'PARTIAL_FEED_SCAN';
  return{records:parsed,allRecords:parsed,verification:{...degradedScanVerification({stamp,feedHash,links,scan:reportScan,state,errorClass}),feedEtag:feed.etag||null,feedLastModified:feed.lastModified||null}};
 }catch(error){return{records:[],allRecords:[],verification:{state:'DEGRADED_UNAVAILABLE',fetchedAt:now.toISOString(),activeCount:null,canSayNoActiveOfficialWarnings:false,parseFailures:null,errorClass:String(error?.message||'SMN_UNAVAILABLE').slice(0,80)}}}
}
export async function inpresFeed(now=new Date()){const url='https://www.inpres.gob.ar/sismos_consultados',r=await safeFetch(url,INPRES),x=parseInpresHtml(r.body,{fetchedAt:now.toISOString(),sourceUrl:url}),cut=now.getTime()-7*86400000,records=x.records.filter(v=>Date.parse(v.observedAt)>=cut);return{records,meta:{observedAt:records.map(v=>v.observedAt).filter(Boolean).sort().at(-1)||null,rawHash:r.rawHash,verification:{...x.verification,sourceRowCount:x.verification.rowCount,recentWindowDays:7,rowCount:records.length}}}}
export async function usgsFeed(now=new Date()){const start=new Date(now.getTime()-7*86400000).toISOString().slice(0,10),end=new Date(now.getTime()+86400000).toISOString().slice(0,10),url=`https://earthquake.usgs.gov/fdsnws/event/1/query?format=geojson&starttime=${start}&endtime=${end}&minlatitude=-55.5&maxlatitude=-20&minlongitude=-74.5&maxlongitude=-52&limit=200&orderby=time`;const r=await safeFetch(url,USGS),x=parseUsgsGeoJson(r.body,{fetchedAt:now.toISOString(),maxFeatures:200});return{records:x.records,meta:{observedAt:x.records.map(v=>v.observedAt).filter(Boolean).sort().at(-1)||null,rawHash:r.rawHash,verification:x.verification}}}
export async function eonetFeed(now=new Date()){const url='https://eonet.gsfc.nasa.gov/api/v3/events?category=wildfires&status=open&days=30&limit=100&bbox=-74.5,-20,-52,-55.5',r=await safeFetch(url,EONET),x=parseEonetWildfires(r.body,{fetchedAt:now.toISOString(),maxEvents:100});return{records:x.records,meta:{observedAt:x.records.map(v=>v.observedAt).filter(Boolean).sort().at(-1)||null,rawHash:r.rawHash,verification:x.verification}}}
async function legacySnapshot(legacy,env){try{const r=await legacy.fetch(new Request('https://local/api/snapshot'),env);if(!r.ok)throw new Error(`LEGACY_${r.status}`);const p=await r.json();return p.data||p}catch{return null}}
function legacyRecordsFromSnapshot(d){if(!d)return[];const out=[];
  for(const s of d.systems||[]){const observed=s.observedAt||null,fetched=s.fetchedAt||d.generatedAt||new Date().toISOString();const fr=s.freshness||freshness(observed,Date.parse(fetched));out.push(publicRecord({recordId:`ina:${s.stationCode||s.id}`,providerId:'ina',providerRecordId:String(s.stationCode||s.id),hazardType:'FLOOD',sourceRole:'OFFICIAL_LOCAL_OR_NATIONAL_OBSERVATION',sourceOrganization:'Instituto Nacional del Agua',official:true,issuedAt:observed||fetched,observedAt:observed,effectiveAt:null,onsetAt:null,expiresAt:null,fetchedAt:fetched,freshness:fr,verificationState:s.available?'VERIFIED_MACHINE':'UNAVAILABLE',geometry:null,bbox:null,regionCodes:['AR-S'],headline:`${s.watercourse||'Río'} · ${s.stationName||''}`.trim(),description:s.currentMetres==null?'Medición no disponible':`Medición ${s.currentMetres} m`,instruction:null,sourceUrl:sourceUrl(d,s.sourceId,'https://www.argentina.gob.ar/ina'),attribution:'Instituto Nacional del Agua (INA)',rawHash:null,stationId:String(s.stationCode||s.id),value:s.currentMetres??null,unit:'m',measurementReference:s.measurementReference||null,trend:s.trend||null,lifecycle:'ACTIVE',elevated:Boolean(s.thresholds?.alert!=null&&s.currentMetres!=null&&s.currentMetres>=s.thresholds.alert)}))}
  const rain=d.rain;if(rain?.available===true&&rain.accumulated1hMm!=null&&freshness(rain.observedAt,Date.parse(rain.fetchedAt||d.generatedAt),45*60000,3*3600000)==='FRESH')out.push(publicRecord({recordId:`nasa-gpm:${rain.observedAt}`,providerId:'nasa-gpm',providerRecordId:rain.observedAt,hazardType:'RAIN',sourceRole:'SUPPLEMENTARY_SATELLITE_ESTIMATE',sourceOrganization:'NASA',official:false,issuedAt:rain.observedAt,observedAt:rain.observedAt,effectiveAt:null,onsetAt:null,expiresAt:rain.validUntil||null,fetchedAt:rain.fetchedAt||d.generatedAt,freshness:'FRESH',verificationState:'SUPPLEMENTARY_MACHINE',geometry:{type:'Point',coordinates:[NASA_POINT.lon,NASA_POINT.lat]},bbox:NASA_POINT.bbox,regionCodes:NASA_POINT.regionCodes,headline:'Estimación satelital de lluvia · Santa Fe',description:`Estimación IMERG ${rain.accumulated1hMm} mm/h; no constituye alerta oficial ni prueba causal sobre el río.`,instruction:null,sourceUrl:sourceUrl(d,rain.sourceId,'https://gpm.nasa.gov/data/imerg'),attribution:'NASA GPM IMERG',rawHash:null,value:rain.accumulated1hMm,unit:'mm/h',lifecycle:'ACTIVE'}));
  return out}
export async function specialistRecords(legacy,env){const snapshot=await legacySnapshot(legacy,env);return{snapshot,records:legacyRecordsFromSnapshot(snapshot)}}
export async function collectNationalState(legacy,env,now=new Date()){const[smn,spec]=await Promise.all([smnFeed({...env,HAZARD_DB:null},now,null),specialistRecords(legacy,env)]);return{records:[...smn.records,...spec.records],smnVerification:smn.verification,legacySnapshot:spec.snapshot}}
function eventView(e){return{...e,records:undefined,sources:e.records}}
function verificationView(v={}){if((v.state==='FRESH_PARSED'||v.state==='FIXTURE_PARSED')&&v.canSayNoActiveOfficialWarnings!==false)return{officialWarningFeed:Number(v.activeCount)>0?'ACTIVE_WARNINGS_VERIFIED':'FRESH_NO_ACTIVE_WARNINGS',verifiedAt:v.fetchedAt||v.verifiedAt||null,activeCount:Number(v.activeCount)||0,canSayNoActiveOfficialWarnings:true};return{officialWarningFeed:'DEGRADED_CANNOT_VERIFY',verifiedAt:v.fetchedAt||v.verifiedAt||null,activeCount:null,canSayNoActiveOfficialWarnings:false,errorClass:v.errorClass||v.state||'UNAVAILABLE'}}
async function verificationFromDb(db){if(!db)return verificationView();const r=await db.prepare("SELECT state,verified_at,active_count,can_say_no_active,error_class FROM provider_verification WHERE provider_id='smn-cap' LIMIT 1").first();return verificationView({state:r?.state,verifiedAt:r?.verified_at,activeCount:r?.active_count,canSayNoActiveOfficialWarnings:r?.can_say_no_active===1,errorClass:r?.error_class})}
async function hasDurableHeartbeat(db){if(!db)return false;try{return!!(await db.prepare("SELECT updated_at FROM runtime_state WHERE key='scheduler:last_cycle' LIMIT 1").first())}catch{return false}}
async function persistedEvents(db,{bbox=null,hazard='',limit=50,offset=0}={}){const rows=(await db.prepare("SELECT payload_json FROM hazard_events WHERE lifecycle='ACTIVE' ORDER BY last_changed_at DESC LIMIT 500").all()).results||[],events=[];for(const row of rows)try{const e=JSON.parse(row.payload_json);if((!bbox||e.bbox&&bboxIntersects(e.bbox,bbox))&&(!hazard||String(e.hazardType).includes(hazard)))events.push(eventView(e))}catch{}events.sort((a,b)=>String(b.lastChangedAt||'').localeCompare(String(a.lastChangedAt||''))||a.eventId.localeCompare(b.eventId));return{events:events.slice(offset,offset+limit),count:events.length}}
async function persistedEvent(db,id){const row=await db.prepare("SELECT payload_json FROM hazard_events WHERE event_id=? LIMIT 1").bind(id).first();if(!row)return null;try{return eventView(JSON.parse(row.payload_json))}catch{return null}}
const SITUATION_ROLE_PRIORITY=['OFFICIAL_WARNING','OFFICIAL_IMPACT_REPORT','OFFICIAL_LOCAL_OR_NATIONAL_OBSERVATION','SUPPLEMENTARY_EXTERNAL_OBSERVATION','SUPPLEMENTARY_EXTERNAL_EVENT_SIGNAL','SUPPLEMENTARY_MODEL_FORECAST','SUPPLEMENTARY_SATELLITE_ESTIMATE','OFFICIAL_STATIC_RISK_CONTEXT','INTERNAL_DERIVATION'];
function situationSource(e){const a=e.sources||e.records||[];return[...a].sort((x,y)=>{const ax=SITUATION_ROLE_PRIORITY.indexOf(x.sourceRole),ay=SITUATION_ROLE_PRIORITY.indexOf(y.sourceRole);return(ax<0?99:ax)-(ay<0?99:ay)||String(x.providerId||'').localeCompare(String(y.providerId||''))||String(x.recordId||'').localeCompare(String(y.recordId||''))})[0]||null}
const situationEvent=e=>{const s=situationSource(e),sources=e.sources||e.records||[],cap=sources.find(x=>x.sourceRole==='OFFICIAL_WARNING'&&['Extreme','Severe','Moderate','Minor'].includes(x.capSeverity))?.capSeverity||null;return{eventId:e.eventId,hazardType:e.hazardType,geometry:e.geometry||null,bbox:e.bbox||null,geometrySemantics:e.geometry?.type||((Array.isArray(e.bbox)&&e.bbox.length===4)?'BBOX_AREA':'NONE'),provinces:e.provinces||[],regions:e.regions||[],officialWarningState:e.officialWarningState||'NONE_VERIFIED',observationState:e.observationState||'NONE',verificationState:s?.verificationState||e.verificationState||null,displaySeverity:e.displaySeverity||null,capSeverity:cap,sourceRole:s?.sourceRole||null,sourceOrganization:s?.sourceOrganization||s?.attribution||s?.providerId||null,freshness:s?.freshness||e.freshness||null,observedAt:s?.observedAt||null,issuedAt:s?.issuedAt||null,fetchedAt:s?.fetchedAt||null,lastChangedAt:e.lastChangedAt||null}};
export async function nationalOverview(db,legacy,env){const generatedAt=new Date().toISOString();if(await hasDurableHeartbeat(db)){const rows=(await db.prepare("SELECT payload_json FROM hazard_events WHERE lifecycle='ACTIVE' ORDER BY last_changed_at DESC LIMIT 500").all()).results||[],events=[];for(const row of rows)try{events.push(JSON.parse(row.payload_json))}catch{}const v=await verificationFromDb(db),byHazard={},byProvince={},earthquakeByRole={};for(const e of events){byHazard[e.hazardType]=(byHazard[e.hazardType]||0)+1;for(const p of e.provinces||[])byProvince[p]=(byProvince[p]||0)+1;if(e.hazardType==='EARTHQUAKE')for(const r of e.records||[])earthquakeByRole[r.sourceRole]=(earthquakeByRole[r.sourceRole]||0)+1}const pvRows=(await db.prepare('SELECT provider_id,state,verified_at,error_class,payload_json FROM provider_verification ORDER BY provider_id LIMIT 50').all()).results||[],providerVerification={};for(const row of pvRows){let detail=null;try{detail=JSON.parse(row.payload_json)}catch{}providerVerification[row.provider_id]={state:row.state,verifiedAt:row.verified_at,errorClass:row.error_class||null,...(detail?{detail}: {})}}return{dataPlane:'DURABLE_D1',dataMode:'DURABLE_D1',generatedAt,verifiedAt:v.verifiedAt,nationalEventCount:events.length,nationalOfficialWarningCount:v.activeCount,nationalActiveOfficialWarnings:v.activeCount,verification:v,countsByHazard:byHazard,countsByProvince:byProvince,activeZoneCount:Object.keys(byProvince).length,recentEarthquakeCount:events.filter(e=>e.hazardType==='EARTHQUAKE').length,recentEarthquakes:events.filter(e=>e.hazardType==='EARTHQUAKE').length,situationEvents:events.slice(0,80).map(situationEvent),earthquakeSourceRoleBreakdown:earthquakeByRole,providerVerification}}
 const state=await collectNationalState(legacy,env,new Date()),events=reconcile(state.records),v=verificationView(state.smnVerification),byHazard={},byProvince={};for(const e of events){byHazard[e.hazardType]=(byHazard[e.hazardType]||0)+1;for(const p of e.provinces||[])byProvince[p]=(byProvince[p]||0)+1}return{dataPlane:'DEGRADED_LIVE_FALLBACK',dataMode:'DEGRADED_LIVE_FALLBACK',generatedAt,verifiedAt:v.verifiedAt,nationalEventCount:events.length,nationalOfficialWarningCount:v.activeCount,nationalActiveOfficialWarnings:v.activeCount,verification:v,countsByHazard:byHazard,countsByProvince:byProvince,activeZoneCount:Object.keys(byProvince).length,recentEarthquakeCount:events.filter(e=>e.hazardType==='EARTHQUAKE').length,recentEarthquakes:events.filter(e=>e.hazardType==='EARTHQUAKE').length,situationEvents:events.slice(0,80).map(situationEvent),earthquakeSourceRoleBreakdown:{},providerVerification:{'smn-cap':state.smnVerification}}}

export async function handleNational(request,env,legacy){const u=new URL(request.url),p=u.pathname,db=env.HAZARD_DB||null;
if(p==='/api/build'&&request.method==='GET')return j({ok:true,data:{releaseId:env.ORDER031_RELEASE_ID||'UNFROZEN',sourceManifestSha256:env.SOURCE_MANIFEST_SHA256||null,distManifestSha256:env.DIST_MANIFEST_SHA256||null,cloudflareVersionId:env.CF_VERSION_METADATA?.id||null,builtAt:env.ORDER031_BUILT_AT||null}});
if(p==='/api/coverage'&&request.method==='GET'){const pub=registryPublic();return j({ok:true,data:{country:'AR',registryVersion:pub.version,capabilities:pub.capabilities}},200,'public, max-age=300')}
if(p==='/api/risk-layers'&&request.method==='GET')return j({ok:true,data:{providerId:'ign-risk',currentImpact:false,notice:'Contexto estático/histórico: no representa afectación actual.',layers:IGN_RISK_LAYERS}},200,'public, max-age=86400');
if(p==='/api/overview'&&request.method==='GET')return j({ok:true,data:await nationalOverview(db,legacy,env)});
if(p==='/api/georef/search'&&request.method==='GET'){const q=(u.searchParams.get('q')||'').trim();if(q.length<2||q.length>80)return safeErr('QUERY_INVALID');const url=`https://apis.datos.gob.ar/georef/api/localidades?nombre=${encodeURIComponent(q)}&max=12&campos=id,nombre,centroide,provincia,departamento,municipio,categoria`;try{const{body}=await safeFetch(url,GEO),x=JSON.parse(body);return j({ok:true,data:{results:(x.localidades||[]).map(v=>({id:v.id,name:v.nombre,province:v.provincia?.nombre||null,department:v.departamento?.nombre||null,municipality:v.municipio?.nombre||null,category:v.categoria,lat:v.centroide?.lat??null,lon:v.centroide?.lon??null}))}},200,'public, max-age=300')}catch{return safeErr('GEOREF_UNAVAILABLE',503)}}
if(p==='/api/snapshot'&&request.method==='GET'){const r=await legacy.fetch(new Request('https://local/api/snapshot'),env),x=await r.json();x.meta={...(x.meta||{}),legacySpecialistScope:'SANTA_FE_HYDROLOGY',nationalWarningStatePath:'/api/overview',legacyAlertStatusNotNational:true};return j(x,r.status)}
 if(p==='/api/observations'&&request.method==='GET'){const type=(u.searchParams.get('type')||'').toUpperCase().slice(0,40),limit=Math.min(100,Math.max(1,Number(u.searchParams.get('limit')||50)||50));let bbox=null;try{if(u.searchParams.get('bbox'))bbox=parseBbox(u.searchParams.get('bbox'))}catch(e){return safeErr(e.message,400)}const now=env.SOS_TEST_NOW?Date.parse(env.SOS_TEST_NOW):Date.now(),snapshot=await legacySnapshot(legacy,env),metadata=await loadInaSeriesMetadata(env,now);let observations=riverObservationsFromSnapshot(snapshot,metadata,now);if(type&&type!=='RIVER_LEVEL')observations=[];if(bbox)observations=observations.filter(o=>o.geometry?.type==='Point'&&o.lon>=bbox[0]&&o.lon<=bbox[2]&&o.lat>=bbox[1]&&o.lat<=bbox[3]);const coordinateState=metadata.length?'AVAILABLE':'UNAVAILABLE',measurementState=snapshot?'AVAILABLE':'UNAVAILABLE',state=measurementState==='AVAILABLE'&&coordinateState==='AVAILABLE'?'AVAILABLE':measurementState==='AVAILABLE'||coordinateState==='AVAILABLE'?'PARTIAL':'UNAVAILABLE';return j({ok:true,data:{observations:observations.slice(0,limit),count:observations.length,limit,sourceState:{providerId:'ina',state,measurementState,coordinateState,freshness:observations.some(o=>o.freshness==='FRESH')?'FRESH':observations.some(o=>o.freshness==='STALE')?'STALE':'UNAVAILABLE',verification:'SOURCE_SCOPED'},coverage:{scope:'DOCUMENTED_STATIONS_ONLY',nationalCoverageClaim:false,adminBoundaryFilter:false,metadataSource:'INA_SIYAH_SERIES_GEOJSON',coordinatePrecision:'PROVIDER_PUBLISHED_UNVALIDATED'}}},200,'public, max-age=60')}
if(p==='/api/events'||p.startsWith('/api/events/')){if(request.method!=='GET'&&request.method!=='HEAD')return safeErr('METHOD_NOT_ALLOWED',405);const detail=p.startsWith('/api/events/'),durable=await hasDurableHeartbeat(db);if(detail){const id=decodeURIComponent(p.slice('/api/events/'.length));if(id.length<1||id.length>240)return safeErr('EVENT_ID_INVALID',400);if(durable){const e=await persistedEvent(db,id);return e?j({ok:true,data:e,meta:{dataPlane:'DURABLE_D1',dataMode:'DURABLE_D1',verification:await verificationFromDb(db)}}):safeErr('EVENT_NOT_FOUND',404)}const state=await collectNationalState(legacy,env),e=reconcile(state.records).map(eventView).find(x=>x.eventId===id);return e?j({ok:true,data:e,meta:{dataPlane:'DEGRADED_LIVE_FALLBACK',dataMode:'DEGRADED_LIVE_FALLBACK',verification:verificationView(state.smnVerification)}}):safeErr('EVENT_NOT_FOUND',404)}let bbox;try{if(!u.searchParams.get('bbox'))return safeErr('BBOX_REQUIRED',400);bbox=parseBbox(u.searchParams.get('bbox'))}catch(e){return safeErr(e.message,400)}const hazard=(u.searchParams.get('hazard')||'').toUpperCase().slice(0,40),limit=Math.min(100,Math.max(1,Number(u.searchParams.get('limit')||50)||50)),offset=Math.max(0,Math.min(1000,Number(u.searchParams.get('offset')||0)||0));if(durable){const x=await persistedEvents(db,{bbox,hazard,limit,offset});return j({ok:true,data:{...x,limit,offset,verification:await verificationFromDb(db)},meta:{dataPlane:'DURABLE_D1',dataMode:'DURABLE_D1'}})}const state=await collectNationalState(legacy,env);let events=reconcile(state.records).map(eventView).filter(e=>e.bbox&&bboxIntersects(e.bbox,bbox));if(hazard)events=events.filter(e=>e.hazardType.includes(hazard));return j({ok:true,data:{events:events.slice(offset,offset+limit),count:events.length,limit,offset,verification:verificationView(state.smnVerification)},meta:{dataPlane:'DEGRADED_LIVE_FALLBACK',dataMode:'DEGRADED_LIVE_FALLBACK'}})}
return null}
export async function enhancedSources(legacy,env){const r=await legacy.fetch(new Request('https://local/api/sources'),env);let p={};try{p=await r.json()}catch{}const pub=registryPublic(),db=env.HAZARD_DB||null;let providerVerification={};if(db)try{const rows=(await db.prepare('SELECT provider_id,payload_json FROM provider_verification ORDER BY provider_id LIMIT 50').all()).results||[];for(const row of rows)try{providerVerification[row.provider_id]=JSON.parse(row.payload_json)}catch{}}catch{}return j({ok:true,data:{legacy:p.data||p,registryVersion:SOURCE_REGISTRY_VERSION,capabilityRegistry:pub.capabilities,providerVerification}})}
export async function enhancedHealth(legacy,env){
 const r=await legacy.fetch(new Request('https://local/api/health'),env);let p={};try{p=await r.json()}catch{}
 const db=env.HAZARD_DB||null;let scheduler=null,providers=[],deadLetters=null,d1QueryState=db?'UNKNOWN':'UNBOUND',d1ErrorClass=null;
 if(db)try{
  scheduler=await runtimeState(db,'scheduler:last_cycle');
  providers=(await db.prepare("SELECT provider_id,status,last_success_at,last_observed_at,error_class,circuit_open_until FROM provider_registry ORDER BY provider_id LIMIT 50").all()).results||[];
  const since7=new Date(Date.now()-7*86400000).toISOString();
  const dl=(await db.prepare("SELECT id FROM provider_jobs WHERE status='DEAD_LETTER' AND finished_at>=? ORDER BY finished_at DESC LIMIT 101").bind(since7).all()).results||[];
  deadLetters=dl.length;
  await db.prepare('SELECT event_id FROM hazard_events LIMIT 1').first();
  d1QueryState='OK';
 }catch(error){d1QueryState='DEGRADED_UNAVAILABLE';d1ErrorClass=String(error?.message||error?.cause?.message||error?.code||'D1_UNAVAILABLE').slice(0,120)}
 const pushConfigured=Boolean(db&&env.VAPID_PUBLIC_KEY&&env.VAPID_PUBLIC_KEY!=='UNCONFIGURED'&&env.VAPID_PRIVATE_JWK&&env.PUSH_STORAGE_KEY);
 const legacyRaw=p.data||p,legacyScoped={...legacyRaw,legacySpecialistScope:'SANTA_FE_HYDROLOGY',nationalWarningStatePath:'/api/overview',legacyAlertStatusNotNational:true,...(legacyRaw?.snapshot?{snapshot:{...legacyRaw.snapshot,alertStatus:'LEGACY_SPECIALIST_STATUS_NOT_NATIONAL'}}:{})};
 return j({ok:true,data:{legacy:legacyScoped,nationalCore:{releaseId:env.ORDER031_RELEASE_ID||'UNFROZEN',registryVersion:SOURCE_REGISTRY_VERSION,ingestionMode:'SINGLE_CRON_PLUS_D1_DURABLE_JOB_TABLE',hazardDbBound:Boolean(db),hazardDbConnected:d1QueryState==='OK',d1QueryState,d1ErrorClass,schedulerLastCycle:scheduler,providers,deadLetterRecentCount:deadLetters,hazardRecordCount:null,hazardEventCount:null,recentEventVersionCount:null,pushSubscriptionCount:null,pushDeliveryAggregates:null,countTelemetryMode:'BOUNDED_NO_FULL_TABLE_COUNTS',pushConfigured,privateMessagingEnabled:false,communityReportingEnabled:false}}})
}