import{SOURCE_REGISTRY,SOURCE_REGISTRY_VERSION,registryPublic,IGN_RISK_LAYERS}from'../providers/registry.js';
import{parseBbox,bboxIntersects,reconcile,freshness,publicRecord}from'../domain/hazard.js';
import{parseInpresHtml}from'../providers/inpres.js';
import{parseUsgsGeoJson}from'../providers/usgs.js';
import{parseEonetWildfires}from'../providers/eonet.js';
import{safeFetch}from'./transport.js';
import{smnFeed,j,safeErr,nationalOverview}from'./national.js';
const INPRES={hosts:['www.inpres.gob.ar'],paths:[/^\/sismos_consultados$/],maxBytes:900000,timeoutMs:8000,contentTypes:['text/html'],accept:'text/html,application/xhtml+xml'};
const USGS={hosts:['earthquake.usgs.gov'],paths:[/^\/fdsnws\/event\/1\/query$/],maxBytes:900000,timeoutMs:8000,contentTypes:['json','geo+json'],accept:'application/geo+json,application/json'};
const EONET={hosts:['eonet.gsfc.nasa.gov'],paths:[/^\/api\/v3\/events$/],maxBytes:900000,timeoutMs:8000,contentTypes:['json','rss+xml'],accept:'application/json'};
const NASA_POINT={lon:-60.7,lat:-31.63,bbox:[-60.75,-31.68,-60.65,-31.58],regionCodes:['AR-S']};
const eventView=e=>({...e,records:undefined,sources:e.records});
export async function fetchInpres(now=new Date()){const url='https://www.inpres.gob.ar/sismos_consultados',x=await safeFetch(url,INPRES);return parseInpresHtml(x.body,{fetchedAt:now.toISOString(),sourceUrl:url})}
export async function fetchUsgs(now=new Date()){const q=new URLSearchParams({format:'geojson',starttime:new Date(now-7*86400000).toISOString(),minlatitude:'-55.5',maxlatitude:'-20',minlongitude:'-74.5',maxlongitude:'-52',orderby:'time',limit:'200'}),x=await safeFetch(`https://earthquake.usgs.gov/fdsnws/event/1/query?${q}`,USGS);return parseUsgsGeoJson(x.body,{fetchedAt:now.toISOString(),maxFeatures:200})}
export async function fetchEonet(now=new Date()){const q=new URLSearchParams({bbox:'-74.5,-20,-52,-55.5',category:'wildfires',status:'open',days:'30',limit:'100'}),x=await safeFetch(`https://eonet.gsfc.nasa.gov/api/v3/events?${q}`,EONET);return parseEonetWildfires(x.body,{fetchedAt:now.toISOString(),maxEvents:100})}
async function legacySnapshot(legacy,env){try{const r=await legacy.fetch(new Request('https://local/api/snapshot'),env);if(!r.ok)return null;const x=await r.json();return x.data||x}catch{return null}}
function srcUrl(s,id,fallback){return(s?.sources||[]).find(x=>x.id===id)?.url||fallback}
function legacyRecords(s){if(!s)return[];const out=[];for(const x of s.systems||[]){const fetched=x.fetchedAt||s.generatedAt||new Date().toISOString(),fr=freshness(x.observedAt,Date.parse(fetched),86400000,604800000);out.push(publicRecord({recordId:`ina:${x.stationCode||x.id}`,providerId:'ina',providerRecordId:String(x.stationCode||x.id),hazardType:'FLOOD',sourceRole:'OFFICIAL_LOCAL_OR_NATIONAL_OBSERVATION',sourceOrganization:'Instituto Nacional del Agua',official:true,issuedAt:x.observedAt||fetched,observedAt:x.observedAt||null,effectiveAt:null,onsetAt:null,expiresAt:null,fetchedAt:fetched,freshness:fr,verificationState:fr==='UNAVAILABLE'?'UNAVAILABLE':'VERIFIED_MACHINE',geometry:null,bbox:null,regionCodes:['AR-S'],headline:`${x.watercourse||'Río'} · ${x.stationName||''}`.trim(),description:x.currentMetres==null?'Medición no disponible':`Medición ${x.currentMetres} m`,instruction:null,sourceUrl:srcUrl(s,x.sourceId,'https://www.argentina.gob.ar/ina'),attribution:'Instituto Nacional del Agua (INA)',rawHash:null,value:x.currentMetres??null,unit:'m',measurementReference:x.measurementReference||null,lifecycle:'ACTIVE'}))}const r=s.rain;if(r?.available===true&&r.accumulated1hMm!=null&&freshness(r.observedAt,Date.parse(r.fetchedAt||s.generatedAt),2700000,10800000)==='FRESH')out.push(publicRecord({recordId:`nasa-gpm:${r.observedAt}`,providerId:'nasa-gpm',providerRecordId:r.observedAt,hazardType:'RAIN',sourceRole:'SUPPLEMENTARY_SATELLITE_ESTIMATE',sourceOrganization:'NASA',official:false,issuedAt:r.observedAt,observedAt:r.observedAt,effectiveAt:null,onsetAt:null,expiresAt:r.validUntil||null,fetchedAt:r.fetchedAt||s.generatedAt,freshness:'FRESH',verificationState:'SUPPLEMENTARY_MACHINE',geometry:{type:'Point',coordinates:[NASA_POINT.lon,NASA_POINT.lat]},bbox:NASA_POINT.bbox,regionCodes:NASA_POINT.regionCodes,headline:'Estimación satelital de lluvia · Santa Fe',description:`Estimación IMERG ${r.accumulated1hMm} mm/h; no es alerta oficial.`,instruction:null,sourceUrl:srcUrl(s,r.sourceId,'https://gpm.nasa.gov/data/imerg'),attribution:'NASA GPM IMERG',rawHash:null,value:r.accumulated1hMm,unit:'mm/h',lifecycle:'ACTIVE'}));return out}
export async function fetchLegacyProvider(legacy,env,id){const s=await legacySnapshot(legacy,env),records=legacyRecords(s).filter(r=>r.providerId===id);return{records,verification:{state:records.length?'FRESH_PARSED':'DEGRADED_UNAVAILABLE',fetchedAt:new Date().toISOString(),recordCount:records.length}}}
function verifyView(v){if(v&&(v.state==='FRESH_PARSED'||v.state==='FIXTURE_PARSED'))return{officialWarningFeed:v.activeCount>0?'ACTIVE_WARNINGS_VERIFIED':'FRESH_NO_ACTIVE_WARNINGS',verifiedAt:v.fetchedAt||v.verifiedAt,activeCount:v.activeCount,canSayNoActiveOfficialWarnings:v.canSayNoActiveOfficialWarnings===true};if(v?.activeCount>0)return{officialWarningFeed:'ACTIVE_WARNINGS_VERIFIED_PARTIAL',verifiedAt:v.fetchedAt||v.verifiedAt,activeCount:v.activeCount,canSayNoActiveOfficialWarnings:false,errorClass:v.errorClass||v.state};return{officialWarningFeed:'DEGRADED_CANNOT_VERIFY',verifiedAt:v?.fetchedAt||v?.verifiedAt||null,activeCount:null,canSayNoActiveOfficialWarnings:false,errorClass:v?.errorClass||v?.state||'NO_VERIFICATION'}}
async function persistedVerification(db,id='smn-cap'){const row=await db.prepare('SELECT payload_json FROM provider_verification WHERE provider_id=?').bind(id).first();if(!row)return null;try{return JSON.parse(row.payload_json)}catch{return null}}
async function loadPersistedEvents(db,{bbox=null,hazard='',limit=50,offset=0}={}){const rows=(await db.prepare("SELECT payload_json FROM hazard_events WHERE lifecycle='ACTIVE' ORDER BY last_changed_at DESC LIMIT 500").all()).results||[];let events=[];for(const row of rows)try{events.push(JSON.parse(row.payload_json))}catch{}if(bbox)events=events.filter(e=>e.bbox&&bboxIntersects(e.bbox,bbox));if(hazard)events=events.filter(e=>String(e.hazardType||'').includes(hazard));const count=events.length;return{events:events.slice(offset,offset+limit).map(eventView),count}}
async function loadPersistedEvent(db,id){const row=await db.prepare('SELECT payload_json FROM hazard_events WHERE event_id=? LIMIT 1').bind(id).first();if(!row)return null;try{return eventView(JSON.parse(row.payload_json))}catch{return null}}
async function directFallback(legacy,env,bbox=null,hazard=''){const state=await import('./national.js').then(m=>m.collectNationalState(legacy,env)),all=reconcile(state.records),events=all.filter(e=>(!bbox||e.bbox&&bboxIntersects(e.bbox,bbox))&&(!hazard||String(e.hazardType).includes(hazard)));return{events:events.map(eventView),verification:verifyView(state.smnVerification),dataMode:'DEGRADED_LIVE_FALLBACK'}}
async function healthDb(env){if(!env.HAZARD_DB)return{hazardDbConnected:false};try{const db=env.HAZARD_DB,beat=await db.prepare("SELECT payload_json,updated_at FROM runtime_state WHERE key='scheduler:last_cycle'").first(),providers=(await db.prepare('SELECT provider_id,status,last_success_at,last_observed_at,error_class,circuit_open_until FROM provider_registry ORDER BY provider_id LIMIT 50').all()).results||[],dead=await db.prepare("SELECT COUNT(*) n FROM provider_jobs WHERE status='DEAD_LETTER'").first(),records=await db.prepare('SELECT COUNT(*) n FROM hazard_records').first(),events=await db.prepare('SELECT COUNT(*) n FROM hazard_events').first(),versions=await db.prepare("SELECT COUNT(*) n FROM event_versions WHERE changed_at>? ").bind(new Date(Date.now()-30*86400000).toISOString()).first(),subs=await db.prepare('SELECT COUNT(*) n FROM push_subscriptions').first();return{hazardDbConnected:true,schedulerLastCycle:beat?.updated_at||null,schedulerState:beat?JSON.parse(beat.payload_json):null,providers,deadLetterCount:Number(dead?.n||0),hazardRecordCount:Number(records?.n||0),hazardEventCount:Number(events?.n||0),recentEventVersionCount:Number(versions?.n||0),pushSubscriptionCount:Number(subs?.n||0)}}catch(error){return{hazardDbConnected:false,errorClass:String(error?.message||'D1_UNAVAILABLE').slice(0,80)}}}
export async function handleOrder031(request,env,legacy){const u=new URL(request.url),p=u.pathname;if(p==='/api/build'&&request.method==='GET')return j({ok:true,data:{releaseId:env.ORDER031_RELEASE_ID||'UNFROZEN',sourceManifestSha256:env.SOURCE_MANIFEST_SHA256||null,distManifestSha256:env.DIST_MANIFEST_SHA256||null,cloudflareVersionId:env.CF_VERSION_METADATA?.id||null,builtAt:env.ORDER031_BUILT_AT||null}});
if(p==='/api/overview'&&request.method==='GET')return j({ok:true,data:await nationalOverview(env.HAZARD_DB||null,legacy,env)});
if(p==='/api/events'||p.startsWith('/api/events/')){if(request.method!=='GET'&&request.method!=='HEAD')return safeErr('METHOD_NOT_ALLOWED',405);const detail=p.startsWith('/api/events/');if(detail){const id=decodeURIComponent(p.slice(12));if(id.length>180)return safeErr('EVENT_ID_INVALID');if(env.HAZARD_DB)try{const e=await loadPersistedEvent(env.HAZARD_DB,id);if(e)return j({ok:true,data:e,meta:{dataMode:'DURABLE_D1',verification:verifyView(await persistedVerification(env.HAZARD_DB))}})}catch{}return safeErr('EVENT_NOT_FOUND',404)}let bbox;try{bbox=parseBbox(u.searchParams.get('bbox'))}catch(e){return safeErr(e.message,400)}if(!bbox)return safeErr('BBOX_REQUIRED',400);const hazard=(u.searchParams.get('hazard')||'').toUpperCase().slice(0,40),limit=Math.min(100,Math.max(1,Number(u.searchParams.get('limit')||50)||50)),offset=Math.max(0,Math.min(1000,Number(u.searchParams.get('offset')||0)||0));if(env.HAZARD_DB)try{const data=await loadPersistedEvents(env.HAZARD_DB,{bbox,hazard,limit,offset}),v=await persistedVerification(env.HAZARD_DB);return j({ok:true,data:{...data,limit,offset,verification:verifyView(v)},meta:{dataMode:'DURABLE_D1'}})}catch{}const f=await directFallback(legacy,env,bbox,hazard);return j({ok:true,data:{events:f.events.slice(offset,offset+limit),count:f.events.length,limit,offset,verification:f.verification},meta:{dataMode:f.dataMode}})}
if(p==='/api/snapshot'&&request.method==='GET'){const r=await legacy.fetch(new Request('https://local/api/snapshot'),env);let x={};try{x=await r.json()}catch{}const d=x.data||x;return j({ok:true,data:{...d,legacySpecialistScope:'SANTA_FE_HYDROLOGY',nationalWarningStateNotRepresented:true},meta:{...(x.meta||{}),legacySpecialistScope:'SANTA_FE_HYDROLOGY',nationalWarningStateNotRepresented:true}})}
if(p==='/api/health'&&request.method==='GET'){const d=await healthDb(env);return j({ok:true,data:{releaseId:env.ORDER031_RELEASE_ID||'UNFROZEN',registryVersion:SOURCE_REGISTRY_VERSION,ingestionMode:'SINGLE_CRON_PLUS_D1_DURABLE_JOB_TABLE',...d,pushConfigured:Boolean(env.HAZARD_DB&&env.VAPID_PUBLIC_KEY&&env.VAPID_PRIVATE_JWK&&env.PUSH_STORAGE_KEY),privateMessagingEnabled:false,communityReportingEnabled:false}})}
if(p==='/api/sources'&&request.method==='GET'){const pub=registryPublic(),db=env.HAZARD_DB;let providerVerification={};if(db)try{const rows=(await db.prepare('SELECT provider_id,payload_json FROM provider_verification ORDER BY provider_id LIMIT 50').all()).results||[];for(const r of rows)try{providerVerification[r.provider_id]=JSON.parse(r.payload_json)}catch{}}catch{}return j({ok:true,data:{registryVersion:SOURCE_REGISTRY_VERSION,capabilityRegistry:pub.capabilities,providerVerification}})}
if(p==='/api/coverage'&&request.method==='GET'){const pub=registryPublic();return j({ok:true,data:{country:'AR',registryVersion:pub.version,capabilities:pub.capabilities}},200,'public, max-age=300')}
if(p==='/api/risk-layers'&&request.method==='GET')return j({ok:true,data:{providerId:'ign-risk',currentImpact:false,notice:'Contexto estático/histórico: no representa afectación actual.',layers:IGN_RISK_LAYERS}},200,'public, max-age=86400');
return null}
