import legacy from'./legacy-baseline.js';
import{handleNational,enhancedHealth,enhancedSources,smnFeed,inpresFeed,usgsFeed,eonetFeed,specialistRecords}from'./national.js';
import{handlePush,dispatchRecordNotifications}from'./push.js';
import{scheduleDueProviders,runDueJobs,persistHazardEvents,writeHeartbeat,cleanupRetention}from'./ingestion.js';
import{reconcile}from'../domain/hazard.js';
import{applyCapLifecycle}from'../providers/cap.js';
export const MAX_JOBS_PER_CYCLE=3;
export async function providerHandler(providerId,env,ctx={}){
 const now=new Date(ctx.now||Date.now());
 if(providerId==='smn-cap'){const x=await smnFeed(env,now,ctx.db||env.HAZARD_DB);return{records:x.allRecords,meta:{observedAt:x.allRecords.map(r=>r.effectivePublicationAt||r.issuedAt).filter(Boolean).sort().at(-1)||null,verification:x.verification,etag:x.verification.feedEtag||null,lastModified:x.verification.feedLastModified||null,rawHash:x.verification.feedHash||null}}}
 if(providerId==='inpres')return inpresFeed(now);
 if(providerId==='usgs-earthquake')return usgsFeed(now);
 if(providerId==='nasa-eonet')return eonetFeed(now);
 if(providerId==='ina'||providerId==='nasa-gpm'){const x=await specialistRecords(legacy,env),records=x.records.filter(r=>r.providerId===providerId);return{records,meta:{observedAt:records.map(r=>r.observedAt||r.issuedAt).filter(Boolean).sort().at(-1)||null,verification:{state:records.length?'FRESH_PARSED':'DEGRADED_UNAVAILABLE',fetchedAt:now.toISOString(),recordCount:records.length}}}}
 throw new Error('PROVIDER_HANDLER_UNKNOWN');
}
export async function rebuildEvents(db,env,now=Date.now()){const baseCutoff=new Date(now-45*86400000).toISOString();let smnCutoff=baseCutoff;try{const row=await db.prepare("SELECT payload_json FROM runtime_state WHERE key='smn:scan' LIMIT 1").first(),scan=row?JSON.parse(row.payload_json):null;if(scan?.completed===true&&scan.startedAt)smnCutoff=scan.startedAt}catch{}const current=new Date(now).toISOString(),smnRows=(await db.prepare("SELECT payload_json,fetched_at FROM hazard_records WHERE provider_id='smn-cap' AND fetched_at>=? AND (expires_at IS NULL OR expires_at>?) ORDER BY fetched_at DESC LIMIT 500").bind(smnCutoff,current).all()).results||[],otherRows=(await db.prepare("SELECT payload_json,fetched_at FROM hazard_records WHERE provider_id IN ('ina','inpres','usgs-earthquake','nasa-eonet','nasa-gpm') AND fetched_at>=? AND (expires_at IS NULL OR expires_at>?) ORDER BY fetched_at DESC LIMIT 500").bind(baseCutoff,current).all()).results||[],rows=[...smnRows,...otherRows].sort((a,b)=>String(b.fetched_at||'').localeCompare(String(a.fetched_at||''))).slice(0,500),records=[];for(const row of rows)try{records.push(JSON.parse(row.payload_json))}catch{}const smn=applyCapLifecycle(records.filter(r=>r.providerId==='smn-cap')),others=records.filter(r=>r.providerId!=='smn-cap'),all=[...smn,...others],events=reconcile(all,new Date(now));await persistHazardEvents(db,events,now);for(const r of smn.filter(x=>x.sourceRole==='OFFICIAL_WARNING'&&x.publicMessage===true&&['Alert','Update','Cancel'].includes(x.capMsgType)))await dispatchRecordNotifications(r,env);return events.length}
export async function scheduledCycle(env,scheduledTime){if(!env.HAZARD_DB)throw new Error('D1_BINDING_REQUIRED_FOR_CANONICAL_DURABLE_MODE');const now=Number.isFinite(Number(scheduledTime))?Number(scheduledTime):Date.now(),scheduled=await scheduleDueProviders(env.HAZARD_DB,now),jobs=await runDueJobs(env.HAZARD_DB,(id,ctx)=>providerHandler(id,env,ctx),{now,limit:MAX_JOBS_PER_CYCLE}),eventCount=await rebuildEvents(env.HAZARD_DB,env,now),retentionDeleted=await cleanupRetention(env.HAZARD_DB,now);const result={mode:'SINGLE_CRON_PLUS_D1_DURABLE_JOB_TABLE',scheduledCount:scheduled.length,jobs,eventCount,retentionDeleted};await writeHeartbeat(env.HAZARD_DB,result,now);return result}
