import type { RiverPoint } from '../../domain/snapshot';
import { fetchProvider, type ProviderPolicy, type ProviderResult } from './core';
const A5: ProviderPolicy=Object.freeze({id:'ina-a5',hosts:Object.freeze(['alerta.ina.gob.ar']),paths:Object.freeze([/^\/a5\/getObservaciones$/]),contentTypes:Object.freeze(['application/json']),maxBytes:1_500_000,refreshMs:5*60_000,freshMs:36*60*60_000,staleMs:365*24*60*60_000});
const WML: ProviderPolicy=Object.freeze({id:'ina-waterml',hosts:Object.freeze(['alerta.ina.gob.ar']),paths:Object.freeze([/^\/a5\/obs\/puntual\/series\/\d+$/]),contentTypes:Object.freeze(['application/xml','text/xml']),maxBytes:1_500_000,refreshMs:5*60_000,freshMs:36*60*60_000,staleMs:365*24*60*60_000});
function record(v:unknown):v is Record<string,unknown>{return typeof v==='object'&&v!==null&&!Array.isArray(v)}
function quality(r:Record<string,unknown>):RiverPoint['quality']{const x=String(r.quality??r.calidad??r.qualifier??'').toLowerCase();return x.includes('valid')||x==='1'||x==='approved'?'PROVIDER_VALIDATED':'PUBLISHED_OPERATIONAL'}
function rest(body:string,id:string):readonly RiverPoint[]{const a=JSON.parse(body) as unknown;if(!Array.isArray(a))throw Error('INA_PARSE');const n=Number(id),o:RiverPoint[]=[];for(const x of a){if(!record(x)||x.tipo!=='puntual'||Number(x.series_id)!==n||typeof x.valor!=='number'||typeof x.timestart!=='string'||!Number.isFinite(Date.parse(x.timestart)))throw Error('INA_PARSE');o.push(Object.freeze({at:new Date(x.timestart).toISOString(),metres:x.valor,measured:true,quality:quality(x)}))}return Object.freeze([...new Map(o.map(x=>[x.at,x])).values()].sort((a,b)=>Date.parse(a.at)-Date.parse(b.at)).slice(-512))}
function waterml(body:string):readonly RiverPoint[]{const o:RiverPoint[]=[];for(const m of body.matchAll(/<(?:\w+:)?MeasurementTVP\b[^>]*>[\s\S]*?<(?:\w+:)?time>([^<]+)<\/(?:\w+:)?time>[\s\S]*?<(?:\w+:)?value>([-+]?\d+(?:[.,]\d+)?)<\/(?:\w+:)?value>[\s\S]*?<\/(?:\w+:)?MeasurementTVP>/gi)){const at=m[1]!,metres=Number(m[2]!.replace(',','.'));if(Number.isFinite(Date.parse(at))&&Number.isFinite(metres))o.push(Object.freeze({at:new Date(at).toISOString(),metres,measured:true,quality:'PUBLISHED_OPERATIONAL'}))}if(!o.length)throw Error('INA_WATERML_PARSE');return Object.freeze(o.sort((a,b)=>Date.parse(a.at)-Date.parse(b.at)).slice(-512))}
export function fetchInaSeries(url:string,providerId:string,id:string):Promise<ProviderResult<readonly RiverPoint[]>>{return fetchProvider(url,{...A5,id:providerId},body=>{const value=rest(body,id),observedAt=value.at(-1)?.at;if(!observedAt)throw Error('INA_EMPTY');return{value,observedAt}})}
export function fetchInaWaterMl(url:string,providerId:string):Promise<ProviderResult<readonly RiverPoint[]>>{return fetchProvider(url,{...WML,id:providerId},body=>{const value=waterml(body),observedAt=value.at(-1)?.at;if(!observedAt)throw Error('INA_WATERML_EMPTY');return{value,observedAt}})}
