import { describe, expect, it } from 'vitest';
import { deriveFloodSituation } from '../../src/domain/flood-situation.ts';
import type { HydrologicalSystem, OfficialAlert, Snapshot, Source } from '../../src/domain/snapshot.ts';

const generatedAt='2026-08-16T06:00:00.000Z';
const validUntil='2026-08-16T18:00:00.000Z';
function system(id: 'parana-santa-fe'|'salado-santo-tome', current: number, alert: number, freshness: HydrologicalSystem['freshness']='ACTUALIZADO'): HydrologicalSystem {
  const watercourse=id.startsWith('parana')?'Río Paraná':'Río Salado'; const station=id.startsWith('parana')?'Santa Fe':'Santo Tomé'; const code=id.startsWith('parana')?'30':'3044';
  return { id,label:`${watercourse} — ${station}`,watercourse,stationName:station,stationCode:code,available:true,dataStatus:freshness==='ACTUALIZADO'?'LIVE':'STALE',freshness,currentMetres:current,observedAt:generatedAt,fetchedAt:generatedAt,validUntil,sourceId:`ina-rest-${code}`,sourceName:'INA',points:[{at:'2026-08-15T06:00:00.000Z',metres:current-.05,measured:true},{at:generatedAt,metres:current,measured:true}],thresholds:[{id:'ALERTA',label:'Nivel de alerta de referencia',metres:alert}],trend:'STABLE',delta1h:null,delta6h:null,delta24h:.05,delta72h:null,delta7d:null };
}
function source(s: HydrologicalSystem): Source { return {id:s.sourceId,name:'INA REST',kind:'OFFICIAL_OBSERVATION',status:'FRESH',observedAt:generatedAt,fetchedAt:generatedAt,validUntil,contribution:'fixture',official:true,connected:true,organizationId:'ina',organizationName:'Instituto Nacional del Agua',classification:'OPERATIONAL_FRESH',freshness:'ACTUALIZADO',determinesPrimaryState:true}; }
function alertSource(status: Source['status']='FRESH'): Source { return {id:'smn-alerts',name:'SMN CAP',kind:'OFFICIAL_ALERT',status,observedAt:generatedAt,fetchedAt:generatedAt,validUntil,contribution:'fixture',official:true,connected:status!=='UNAVAILABLE',organizationId:'smn',organizationName:'Servicio Meteorológico Nacional',classification:status==='UNAVAILABLE'?'DEGRADED':'OPERATIONAL_FRESH',freshness:status==='UNAVAILABLE'?'NO_DISPONIBLE':'ACTUALIZADO',determinesPrimaryState:true}; }
function base(systems: HydrologicalSystem[]): Snapshot {
  const p=systems[0]!; return {schemaVersion:'1.0',id:'fixture',mode:'LIVE',generatedAt,previousSnapshotAt:generatedAt,state:'NORMAL',stateLabel:'fixture',summary:'fixture',dominantSourceId:p.sourceId,validUntil,recommendedAction:'fixture',emergencyDisclaimer:'fixture',alertStatus:'SIN_ALERTAS_OFICIALES_DETECTADAS',alerts:[],changes:[],systems,river:{systemId:p.id,available:true,stationName:p.stationName,currentMetres:p.currentMetres,delta1h:p.delta1h,delta6h:p.delta6h,delta24h:p.delta24h,trend:p.trend,observedAt:p.observedAt!,fetchedAt:p.fetchedAt!,validUntil,sourceId:p.sourceId,points:p.points,forecastPoints:[],thresholds:p.thresholds},rain:{accumulated1hMm:null,accumulated24hMm:null,forecast:'none',observedAt:generatedAt,fetchedAt:generatedAt,validUntil,sourceId:'rain-none',points:[]},sources:[...systems.map(source),alertSource()],contradictions:[],shelters:[],actions:[],messages:[]};
}
function officialAlert(headline='Alerta por lluvias intensas'): OfficialAlert { return {identifier:'a1',sender:'SMN',sent:generatedAt,status:'Actual',messageType:'Alert',scope:'Public',category:'Met',event:'Tormentas',urgency:'Expected',severity:'Moderate',certainty:'Likely',effective:generatedAt,onset:generatedAt,expires:validUntil,headline,description:'Lluvias intensas en Santa Fe',instruction:'Seguir indicaciones oficiales',area:'Santa Fe',sourceUrl:'https://www.smn.gob.ar/alertas',lifecycle:'ACTIVE',appliesToSantaFe:true}; }

describe('028 flood situation engine', () => {
  it('routine fresh rivers stays routine', () => { const d=deriveFloodSituation(base([system('parana-santa-fe',3.2,5.3),system('salado-santo-tome',3.4,4.7)])); expect(d.state).toBe('ROUTINE'); expect(d.officialEmergencyDeclared).toBe(false); });
  it('one protection reference produces relevant situation, never official emergency', () => { const d=deriveFloodSituation(base([system('parana-santa-fe',5.35,5.3),system('salado-santo-tome',3.4,4.7)])); expect(d.state).toBe('FLOOD_SITUATION'); expect(d.affectedSystemIds).toEqual(['parana-santa-fe']); expect(d.officialEmergencyDeclared).toBe(false); });
  it('dual material relevance preserves both systems', () => { const d=deriveFloodSituation(base([system('parana-santa-fe',5.35,5.3),system('salado-santo-tome',4.75,4.7)])); expect(d.state).toBe('FLOOD_SITUATION'); expect(d.affectedSystemIds).toHaveLength(2); });
  it('official heavy-rain warning does not fabricate river emergency', () => { const snap=base([system('parana-santa-fe',3.2,5.3),system('salado-santo-tome',3.4,4.7)]); const withAlert: Snapshot={...snap,alertStatus:'ALERTA_OFICIAL_ACTIVA',alerts:[officialAlert()]}; const d=deriveFloodSituation(withAlert); expect(d.state).toBe('OFFICIAL_WARNING_ACTIVE'); expect(d.affectedSystemIds).toHaveLength(0); expect(d.officialEmergencyDeclared).toBe(false); });
  it('model signal alone cannot create official warning or emergency', () => { const snap=base([system('parana-santa-fe',3.2,5.3),system('salado-santo-tome',3.4,4.7)]); const withModel: Snapshot={...snap,sources:[...snap.sources,{id:'model',name:'model',kind:'FORECAST_MODEL',status:'FRESH',observedAt:generatedAt,fetchedAt:generatedAt,validUntil,contribution:'fixture',official:false,connected:true,freshness:'ACTUALIZADO',determinesPrimaryState:false}]}; const d=deriveFloodSituation(withModel); expect(d.state).toBe('ROUTINE'); expect(d.officialWarningActive).toBe(false); expect(d.officialEmergencyDeclared).toBe(false); });
  it('stale hydrometry cannot activate a material situation', () => { const stale=system('parana-santa-fe',6,5.3,'DESACTUALIZADO'); const snap=base([stale,system('salado-santo-tome',3.4,4.7)]); const degraded: Snapshot={...snap,sources:[source(stale),source(snap.systems![1]!),alertSource()]}; const d=deriveFloodSituation(degraded); expect(d.state).toBe('VERIFICATION_DEGRADED'); expect(d.affectedSystemIds).toHaveLength(0); });
  it('unavailable alert verification never yields false normal', () => { const snap=base([system('parana-santa-fe',3.2,5.3),system('salado-santo-tome',3.4,4.7)]); const degraded: Snapshot={...snap,alertStatus:'FUENTES_DE_ALERTAS_NO_DISPONIBLES',sources:[...snap.sources.filter(s=>s.id!=='smn-alerts'),alertSource('UNAVAILABLE')]}; const d=deriveFloodSituation(degraded); expect(d.state).toBe('VERIFICATION_DEGRADED'); expect(d.officialEmergencyDeclared).toBe(false); });
  it('community report only never changes official state', () => { const snap=base([system('parana-santa-fe',3.2,5.3),system('salado-santo-tome',3.4,4.7)]); const withCommunity: Snapshot={...snap,sources:[...snap.sources,{id:'community',name:'Reporte',kind:'COMMUNITY_REPORT',status:'FRESH',observedAt:generatedAt,fetchedAt:generatedAt,validUntil,contribution:'fixture',official:false,connected:true,freshness:'ACTUALIZADO',determinesPrimaryState:false}]}; const d=deriveFloodSituation(withCommunity); expect(d.state).toBe('ROUTINE'); expect(d.officialEmergencyDeclared).toBe(false); });
});
